Add full command to extras
getsentry/sentry-symfony pull request #352
Opened 2020-06-28 15:18 UTC by ostrolucky

Fixes #351

2021-01-11 17:18 UTC, Jean85 commented
@ste93cry do you think we should recover this into the 4.0 release? Take a look at the discussion in #351 too.

2021-01-14 20:02 UTC, ste93cry commented
I'm generally favourable to adding logging of the command. Regarding the sanitization, As it's a full string I don't think that Sentry can hide or detect specific portions of it so that values of certain command arguments or options will be hidden... I wonder anyway why someone would pass sensitive data as an argument or option, since it would be visible in the CLI as much as in any log system. Bonus question: I'm really doubtful about whether the command should be logged in the extra context or as a breadcrumb

2021-01-15 12:20 UTC, ostrolucky commented
According link in linked issue, laravel also passes whole thing as string, so I don't believe this is an issue. 

As for breadcrumbs, in my pov breadcrumbs are something which happens in sequence, like a log. I think command name does not quite fit in that definition, similarly like request url and so on. Especially when command name already is a tag instead of bread crumb and I'm implementing now just logging of full command name - but I deemed full command name being too unique for being a tag, hence second best was extra.

2021-01-16 00:24 UTC, ste93cry commented
>As for breadcrumbs, in my pov breadcrumbs are something which happens in sequence, like a log. I think command name does not quite fit in that definition, similarly like request url and so on

True, but in Symfony the concept of subrequest exists as it exists the concept of a command started and running within another. I would say that logging as bredcrumbs both the start of a request and of a command would be useful. Anyway, I agree that at the moment logging the full command in the extras is enough

>I deemed full command name being too unique for being a tag

Absolutely agree with this claim

2021-04-04 17:28 UTC, ste93cry requested changes

2021-04-04 17:28 UTC, ste93cry commented on tests/End2End/End2EndTest.php
> +    public function testCommand(): void
Rather than an integration test I would expect the unit tests of the `ConsoleCommandListener` class to be updated

2021-04-04 18:37 UTC, ostrolucky commented on tests/End2End/End2EndTest.php
> +    public function testCommand(): void
Unit test wouldn't test if command name was captured. For example, there is no guarantee input type that is received in listener won't be changed in future to something else than ArgvInput. But in unit test we would have to hardcode ArgvInput mock, so change won't be picked up. End2end test is more useful here; also as future basis, as currently there are no end2end command tests. Would be shame to throw that work away.

2021-04-06 10:13 UTC, Jean85 requested changes
LGTM :+1: but please add a changelog entry

2021-04-10 14:05 UTC, ste93cry commented on tests/End2End/End2EndTest.php
> +    public function testCommand(): void
There is no relation between the presence of the command name in the logged string and the code of the listener in my opinion: the only thing that it does is casting the input object to a `string`. I don't say that this e2e should be removed, but I would like to add a unit test too for coherence, even if now they overlaps

2021-04-10 17:24 UTC, ostrolucky commented on tests/End2End/End2EndTest.php
> +    public function testCommand(): void
Ok, unit test added

2021-04-12 07:59 UTC, Jean85 commented
Build should be fixed by #480, but there are conflicts now.

2021-04-12 15:38 UTC, ostrolucky commented
rebased

2021-04-12 15:48 UTC, ste93cry approved these changes

2021-04-12 20:43 UTC, Jean85 approved these changes

2021-04-12 20:43 UTC, merged