Make command lazily loaded
getsentry/sentry-symfony pull request #373
Opened 2020-09-21 13:37 UTC by kefzce

Hi there.
Science Symfony 3.4^ [allows us to provide console command name for compile-time registration](https://github.com/symfony/symfony/pull/23887) all console command should be registered by this way, if not
every time when someone run ./bin/console Symfony should compile all container to fetch command name and [set parameter manually ](https://github.com/symfony/symfony/blob/6f81e033312f5feb744507766d02f2e8cae01e9b/src/Symfony/Component/Console/DependencyInjection/AddConsoleCommandPass.php#L96)

Also here is a way to check if on your Symfony project some commands register not properly
```bash
bin/console debug:container --parameter=console.command.ids
```
Example output from my project now
``` --------------------- ----------------------------------------------------------------- 
  Parameter             Value                                                            
 --------------------- ----------------------------------------------------------------------------- ------------ 
  console.command.ids   ["console.command.public_alias.Sentry\SentryBundle\Command\SentryTestCommand
 --------------------- ------------------------------------------------------------------------------------------
```
we are using        
``` "sentry/sentry-symfony": "^3.0" // 3.5.2 ```
This is the simple fix don't break anything because BC layer already on \Symfony\Component\Console\Command\Command

Also here some ref where the same problem was fixed by this way

- https://github.com/doctrine/migrations/pull/839
- https://github.com/doctrine/DoctrineMongoDBBundle/pull/642

btw, I'm not sure about the target branch, should be 3.5 instead?

2020-09-21 13:42 UTC, za4me approved these changes
LGTM!

2020-09-21 13:44 UTC, AMATORIK approved these changes

2020-09-21 14:03 UTC, Jean85 requested changes
Change LGTM :+1: but I had to change the target branch, so you should drop the additional commits from master.

Please also add a changelog entry too.

2020-09-21 15:06 UTC, kefzce commented
> Change LGTM 👍 but I had to change the target branch, so you should drop the additional commits from master.
> 
> Please also add a changelog entry too.

Sure, thanks ill rebase pr a bit later from the target branch.

2020-11-07 21:21 UTC, ste93cry commented
Can you please rebase once more and fix the broken build (it should be enough to change the regex of the error message of PHPStan so that instead of hardcoding the version number uses a match pattern)?

2020-11-07 21:25 UTC, kefzce commented
> Can you please rebase once more and fix the broken build (it should be enough to change the regex of the error message of PHPStan so that instead of hardcoding the version number uses a match pattern)? Also, in the CHANGELOG can you please add a reference to this PR?

Sure. no problem.

2020-11-09 08:23 UTC, Jean85 approved these changes

2020-11-09 08:23 UTC, merged

2020-11-09 08:23 UTC, Jean85 commented
Thank you for your contribution!