Support PHPUnit 9
getsentry/sentry-symfony pull request #389
Opened 2020-11-18 19:42 UTC by W0rma

One step closer towards PHP 8 support...

Related to https://github.com/getsentry/sentry-symfony/issues/364

* drop support for PHP 7.1
* add support for PHPUnit 9 which itself supports PHP 8

2020-11-18 20:38 UTC, Jean85 requested changes
Thanks for the PR! Please take care of the build errors..

2020-11-18 20:38 UTC, Jean85 commented on test/BaseTestCase.php
> +        protected function getSupportedOptionsCount(): int
Are you duplicating the code here? Wouldn't be easier to put an ancestor class with only the trait before this one?

2020-11-19 08:17 UTC, W0rma commented on test/BaseTestCase.php
> +        protected function getSupportedOptionsCount(): int
You are right - fixed. Thank you for the hint

2020-11-19 08:22 UTC, W0rma commented
> Thanks for the PR! Please take care of the build errors..

I bumped `symfony/framework-bundle` version to ^3.4.23 which fixes the compatibility issue with older versions of PHPUnit. Tests are green locally. I don't know why the CI build in "prefer lowest" is still failing. Do I need to do something here?

2020-11-19 08:41 UTC, Jean85 commented
Is still see `Installing symfony/framework-bundle (v3.4.0)` in the build, that's strange...
https://github.com/getsentry/sentry-symfony/pull/389/checks?check_run_id=1422948218#step:7:300

2020-11-19 13:59 UTC, W0rma commented
Thank you for the hint - I was able to fix the pipeline

2020-11-19 14:25 UTC, Jean85 approved these changes

2020-11-19 14:26 UTC, merged

2020-11-19 14:26 UTC, Jean85 commented
Thank you for your contribution!