Refactor the bundle configuration and add support for XML format
getsentry/sentry-symfony pull request #401
Opened 2020-12-18 21:00 UTC by ste93cry

With this PR I did a few things, namely:

- Added support for the XML format to the bundle configuration
- Refactored the tests to make them more reliable and improved the code to make it simpler and more readable
- Removed legacy code that was added to support the various features introduced with each `2.x` version
- Refactored how and which container services are registered

2020-12-19 21:51 UTC, Jean85 reviewed
On a first glance, this LGTM, but I need to delve a little more locally, with an IDE.

Unrotunately, the build is still having issues, and I'm making no progress on #400 :cry:

2020-12-19 23:25 UTC, ste93cry commented
>Unfortunately, the build is still having issues, and I'm making no progress on #400 :cry: 

Yep I know, some failures of this build are not related to the broken CI anyway. I'm working to fix as much as I can and then I will take a look at the rest. Since the last commit on master is green, something must have changed in the last few versions of PHPStan

2020-12-22 07:43 UTC, Jean85 commented on src/DependencyInjection/Configuration.php
> +                        ->scalarNode('logger')->end()
Shouldn't this be a service?

2020-12-22 07:54 UTC, Jean85 requested changes

2020-12-22 07:54 UTC, Jean85 commented on src/DependencyInjection/SentryExtension.php
> +        $serializerDefinition->setArgument(0, new Reference('sentry.client.options'));
Why this mixed approach in passin the options once as value, twice as reference (created multiple times too)?

2020-12-22 07:54 UTC, Jean85 commented on src/DependencyInjection/SentryExtension.php
> +            throw new LogicException(sprintf('To use the "%s" class you need to require the "monolog/monolog" package.', Handler::class));
I'm not sure that's the right package to require in a Symfony app...

2020-12-22 07:54 UTC, Jean85 commented on src/ErrorTypesParser.php
> -class ErrorTypesParser
This is an undocumented BC: before it would work as a string, now you need the `!php/const` format.

But I'm :-1: on this, because in this way I don't think you can use binary operators to obtain something like `E_ALL & ~E_DEPRECATED` as before.

2020-12-22 12:29 UTC, ste93cry commented on src/DependencyInjection/SentryExtension.php
> +        $serializerDefinition->setArgument(0, new Reference('sentry.client.options'));
I think you confused things a bit. What it's being done here is that the `sentry.client.options` service is created and the raw options parsed from the bundle configuration are passed to its constructor. Then, such service is referenced in the constructor of the other two services

2020-12-22 12:31 UTC, ste93cry commented on src/DependencyInjection/SentryExtension.php
> +            throw new LogicException(sprintf('To use the "%s" class you need to require the "monolog/monolog" package.', Handler::class));
Technically speaking one could also use Monolog without the bundle as it's the only required thing to make our handler work, but for simplicity we may want to suggest the bundle instead of the base library

2020-12-25 19:42 UTC, ste93cry commented on src/ErrorTypesParser.php
> -class ErrorTypesParser
I reverted the change, but I also refactorized the class to make it `static` 👍

2020-12-27 21:31 UTC, Jean85 requested changes

2020-12-27 21:31 UTC, Jean85 commented on README.md
> -The 3.0 version of the bundle uses the newest version (2.x) of the underlying Sentry SDK. If you need to migrate from previous versions, please check the `UPGRADE-3.0.md` document.
I would leave at least a not with a link to the UPGRADE documents

2020-12-27 21:31 UTC, Jean85 commented on UPGRADE-4.0.md
> +- Changed the type of the `sentry.options.before_send` configuration option from `scalar` to `string`. The value must always be the name of the container service to call without the `@` prefix.
Why did you drop the callable format? Was it harder to maintain?

2020-12-27 21:31 UTC, Jean85 commented on composer.json
> +        "symfony/security-core": "^3.4.43||^4.4.11||^5.0.11"
Does Symfony 5.1.0 support PHP 8 correctly?

2020-12-27 21:31 UTC, Jean85 commented on src/DependencyInjection/Configuration.php
> +                        ->integerNode('send_attempts')->min(0)->end()
Does `0` make sense here?

2020-12-27 21:31 UTC, Jean85 commented on src/DependencyInjection/Configuration.php
> +                            ->max(Options::DEFAULT_MAX_BREADCRUMBS)
Why? Can't I send more?

2020-12-27 21:31 UTC, Jean85 commented on src/DependencyInjection/Configuration.php
> +                            ->defaultValue(['%kernel.cache_dir%', '%kernel.build_dir%', '%kernel.project_dir%/vendor'])
Should we split this in multiple lines for easier git diff?

2020-12-27 21:31 UTC, Jean85 commented on src/DependencyInjection/SentryExtension.php
> +            ->addMethodCall('setSdkVersion', [PrettyVersions::getRootPackageVersion()->getPrettyVersion()])
This is wrong: this package is NOT the root package when in use.

2020-12-27 21:31 UTC, Jean85 commented on src/DependencyInjection/SentryExtension.php
> +        return $integrations;
Wouldn't a custom sort function be more clear here?

2020-12-27 21:31 UTC, Jean85 commented on src/ErrorTypesParser.php
> +                return constant($matches[1]);
This generates a warning in case of failure. That's bad.

https://www.php.net/manual/en/function.constant.php#refsect1-function.constant-errors

2020-12-27 22:39 UTC, ste93cry commented on composer.json
> +        "symfony/security-core": "^3.4.43||^4.4.11||^5.0.11"
Yes, it does since some commit between RC1 and RC2. To be honest I didn't really investigated, I just copied the constraints from the `composer.json` of the main SDK

2020-12-27 22:40 UTC, ste93cry commented on src/DependencyInjection/Configuration.php
> +                            ->max(Options::DEFAULT_MAX_BREADCRUMBS)
No, as you can see [here](https://github.com/getsentry/sentry-php/blob/490952f8b1c752fa8297af6d7dcdc789b7042320/src/Options.php#L854)

2020-12-27 22:41 UTC, ste93cry commented on src/DependencyInjection/SentryExtension.php
> +            ->addMethodCall('setSdkVersion', [PrettyVersions::getRootPackageVersion()->getPrettyVersion()])
Right, I didn't think about it when I wrote the code

2020-12-27 22:45 UTC, ste93cry commented on src/ErrorTypesParser.php
> +                return constant($matches[1]);
It doesn't because the function call is wrapped around the `defined(...)` check

2020-12-27 22:48 UTC, ste93cry commented on src/DependencyInjection/Configuration.php
> +                        ->integerNode('send_attempts')->min(0)->end()
Yes, setting it to that value disables the sending retrial feature. Also, side note, I read somewhere on Discord that there was a discussion regarding the fact that events should simply get lost if the sending is unsuccessful

2020-12-27 22:50 UTC, ste93cry commented on src/DependencyInjection/Configuration.php
> +                            ->defaultValue(['%kernel.cache_dir%', '%kernel.build_dir%', '%kernel.project_dir%/vendor'])
As you prefer, I don't have a strong opinion on this because I don't think it's something that will change in the foreseeable future

2020-12-27 22:53 UTC, ste93cry commented on src/DependencyInjection/SentryExtension.php
> +        return $integrations;
What does sorting have to do with this code 🤔? What I'm doing is to add the `IgnoreErrorsIntegration` integration only if it wasn't already defined in the `integrations` option to avoid overriding the one configured by the user and only if the Sentry error handler is enabled to avoid skipping the log of fatal errors in case the user is using Monolog

2020-12-27 22:59 UTC, ste93cry commented on UPGRADE-4.0.md
> +- Changed the type of the `sentry.options.before_send` configuration option from `scalar` to `string`. The value must always be the name of the container service to call without the `@` prefix.
It is indeed harder to handle this syntax across all the configuration formats (e.g. XML) than having a simple string referencing the ID of a service, but that was not my main reason: the main reason is that I wanted to avoid having a syntax specifically of PHP in the configuration files and I don't know any bundle that allows this, so I thought that it was better to step back and just support one kind of syntax that is widely known in the Symfony ecosystem

2020-12-28 08:35 UTC, Jean85 commented on src/DependencyInjection/Configuration.php
> +                            ->defaultValue(['%kernel.cache_dir%', '%kernel.build_dir%', '%kernel.project_dir%/vendor'])
It already changed recently due to changes in Symfony folder structure. It could happen again.

2020-12-28 08:35 UTC, Jean85 commented on src/DependencyInjection/SentryExtension.php
> +        return $integrations;
Oh right, you're only adding it, not sorting it if present.

2020-12-28 12:31 UTC, ste93cry commented on src/DependencyInjection/Configuration.php
> +                            ->defaultValue(['%kernel.cache_dir%', '%kernel.build_dir%', '%kernel.project_dir%/vendor'])
Yes, but as I said I don't expect it to change anytime soon. Anyway, I split each value into its own line

2020-12-28 12:34 UTC, ste93cry commented on README.md
> -The 3.0 version of the bundle uses the newest version (2.x) of the underlying Sentry SDK. If you need to migrate from previous versions, please check the `UPGRADE-3.0.md` document.
I reverted the change and changed the phrase to refer to the 4.0 version since this is what the branch is based on

2020-12-28 17:07 UTC, ste93cry commented on README.md
>   * 2.x is supported only for fixes; from this version onwards it requires Symfony 3+ and PHP 7.1+;
@Jeans85, now that we are going to release 4.x, what are your plans for `2.x`? I would stop maintaining it and follow the same strategy of the main SDK which is to support only the latest two releases, even if we never documented or said anything about this policy in an official way

2020-12-30 21:00 UTC, Jean85 commented on README.md
>   * 2.x is supported only for fixes; from this version onwards it requires Symfony 3+ and PHP 7.1+;
2.x works with the 1.x SDK... But I never received an issue on that since 3.0 was released, since it has the same PHP/Symfony requirements.

We could do critical fixes only for both 2 and 3... WDYT?

2020-12-30 21:28 UTC, ste93cry commented on README.md
>   * 2.x is supported only for fixes; from this version onwards it requires Symfony 3+ and PHP 7.1+;
Considering that `1.x` of the SDK is not maintained anymore and we didn't receive any issue since a long time, I find useless and time consuming to commit supporting `2.x` of this bundle, but I will leave the final decision to you as you are the main contributor here

2020-12-31 08:43 UTC, Jean85 commented on README.md
>   * 2.x is supported only for fixes; from this version onwards it requires Symfony 3+ and PHP 7.1+;
Oh I thought 1.x was still somehow maintained... I'm fine with dropping support for it then, and urgent bugfix for 3.x only :+1:

2020-12-31 08:50 UTC, ste93cry commented on README.md
>   * 2.x is supported only for fixes; from this version onwards it requires Symfony 3+ and PHP 7.1+;
>Oh I thought 1.x was still somehow maintained

The README still says that that version is maintained for security updates, in reality noone cares anymore about that version. Given that it's two years since the release of the SDK `2.x` and that PHP5 is EOL since when I don't even remember, it's worth in my opinion to officially declare the end of the support for that version and to focus on improving/maintaining the newer versions

2021-01-02 16:21 UTC, Jean85 approved these changes

2021-01-02 16:21 UTC, merged