Reorganize the folder structure and apply new CS standard
getsentry/sentry-symfony pull request #405
Opened 2021-01-04 13:00 UTC by ste93cry

As per title, I've aligned both the CS standard and the folder structure with the one used in the main SDK. The only notable change is the introduction of `declare(strict_types=1)` in all files. I also deleted the whole `examples` folder as I judged it useless, unmaintained, and because I think it's better to improve the documentation rather than providing yet another copy of a basic Symfony app that I don't understand how it can help new users

2021-01-04 17:33 UTC, Jean85 commented
> I also deleted the whole examples folder as I judged it useless, unmaintained, and because I think it's better to improve the documentation rather than providing yet another copy of a basic Symfony app that I don't understand how it can help new users

I agree: the End2End tests serve the same purposes and are automatically aligned with the code.

2021-01-04 20:01 UTC, Jean85 requested changes

2021-01-05 11:35 UTC, ste93cry commented on phpunit.xml
> +         xsi:noNamespaceSchemaLocation="vendor/phpunit/phpunit/phpunit.xsd"
I avoided the external resource by pointing the location to the lowest schema available, which is the one it would use PHPUnit in case

2021-01-05 18:30 UTC, Jean85 approved these changes

2021-01-05 18:30 UTC, merged