Remove the listener priorities configuration options
getsentry/sentry-symfony pull request #407
Opened 2021-01-10 21:27 UTC by ste93cry

I know we discussed about removing these configuration options in the past, but I strongly believe that this kind of things should not be part of the bundle configuration mainly for these reasons:

- There is already a way to change this kind of things, which is writing a compiler pass or overriding the service
- I think that it's not a common thing to change this, in a lot of years of work with Symfony I rarely if never had to change the priority of a third-party listener
- Exposing this configuration to users puts it on an equal footing with changing any bundle or SDK option, which is false because it affects the inner workings of the bundle itself
- The listeners (for example the tracing listener I would like to implement in the near future) must run in a specific priority which correlates them. Letting users change such priorities will likely break things because they must know that they must also update all related priorities: at that point, you're falling into an advanced use-case which to me means that you also have the knowledge to implement the proper solution

2021-01-11 08:26 UTC, Jean85 requested changes

2021-01-11 08:26 UTC, Jean85 commented on CHANGELOG.md
> +- [BC BREAK] Remove the `listener_priorities` configuration option. Instead, use a compiler pass to change the priority of the listeners (#)
Issue number missing.
```suggestion
- [BC BREAK] Remove the `listener_priorities` configuration option. Instead, use a compiler pass to change the priority of the listeners (#407)
```

2021-01-11 08:26 UTC, Jean85 commented on UPGRADE-4.0.md
> +- Removed the `sentry.listener_priorities` configuration option.
We could add an example (before/after) on how to do that, since it's a couple lines of code

2021-01-11 08:26 UTC, Jean85 commented on composer.json
> +        "symfony/polyfill-php80": "^1.22",
Why are we requiring this directly?

2021-01-11 12:05 UTC, ste93cry commented on composer.json
> +        "symfony/polyfill-php80": "^1.22",
PHPStan was complaining on some tests that an anonymous class was passed to a function accepting only a `Stringable` object, so I had to implement that interface interface and thus we need the polyfill

2021-01-11 13:55 UTC, Jean85 commented on composer.json
> +        "symfony/polyfill-php80": "^1.22",
Then you should require it as `require-dev` at the very least.

2021-01-11 17:10 UTC, ste93cry commented on composer.json
> +        "symfony/polyfill-php80": "^1.22",
Done 👍

2021-01-11 17:16 UTC, Jean85 approved these changes

2021-01-11 17:16 UTC, merged

2023-05-25 18:35 UTC, futuster commented on UPGRADE-4.0.md
> +- Removed the `sentry.listener_priorities` configuration option.
> Letting users change such priorities will likely break things because they must know that they must also update all related priorities

Yeah, an example would be great