WIP: Initial implementation of sentry tracing with twig and doctrine support
getsentry/sentry-symfony pull request #423
Opened 2021-01-22 15:22 UTC by rjd22

This is my initial experimental implementation of tracing. It is unfinished because it connects quite directly to the dependencies of the project.

# Todo
- [ ] Don't connect tracing Classes when tracing is not enabled (not sure what would be preferred)
- [ ] Make Doctrine optional by somehow checking it it's used (not sure how to do this ATM)
- [ ] Make Twig optional by somehow checking it it's used (not sure how to do this ATM)
- [ ] Add proper support for Symfony < 4.4 (I can't seem to figure out how the events match)
- [ ] Am I forgetting something?

2021-01-22 17:31 UTC, ste93cry commented
Thank you for the willingness of contributing! May I ask you to split each feature (the request tracing listener, the Twig tracing listener, etc) into its own PR? This way, it will be both easier to review the code and we can develop them independently without necessarily having to rush for the release of all of them at the same time

2021-01-22 17:44 UTC, rjd22 commented
@ste93cry Thank you for your feedback. This is an really good idea. I will split them up later.

2021-01-24 14:58 UTC, rjd22 commented on phpstan.neon
> +        - tests/EventListener/Tracing/RequestListenerTest.php
You might frown on this but, the test caused so many PHPStan errors because of missing classes it made my head spin.

2021-01-24 15:01 UTC, rjd22 commented
@ste93cry I splitted off the dbal and twig tracing support and added tests. Testing was quite complex and took me too much time. I'm not planning to invest more of my time into this except for small changes since I'm not getting paid for this.

2021-01-24 16:48 UTC, stayallive commented
I'll let @ste93cry and @Jean85 actually comment on the code but looking as a non-symfony dev this looks pretty nice already!

I wanted to at least have thanked you for taking the time to get this started, this is a huge help and very much appreciated. I'm sure Stefano and Alessandro will be able to get this in with this head-start, thanks!

2021-01-24 21:04 UTC, rjd22 commented
I also made an PR for dbal tracing:
https://github.com/getsentry/sentry-symfony/pull/426

2021-01-26 11:53 UTC, rjd22 commented
Closing and reopened to trigger build

2021-02-17 17:16 UTC, ste93cry commented
Are you willing to rebase this PR so that we can proceed with reviewing it?

2021-02-17 17:20 UTC, rjd22 commented
@ste93cry yep I will do so later.

2021-02-23 10:56 UTC, rjd22 commented
@Jean85 did you mean to merge master into this branch? Since it was based on develop.

2021-02-23 11:52 UTC, Jean85 commented
> @Jean85 did you mean to merge master into this branch? Since it was based on develop.

Crap, that's what I was doing wrong!
Fixing it, in progress!

2021-02-23 12:06 UTC, Jean85 commented
Ok I force pushed reverting back to a4b5fb3 which was the last commit before my screw up.
I'll attempt to correctly rebase now.

2021-02-23 12:14 UTC, Jean85 commented
Nope, the right one was 9978c35, and it correctly didn't have any conflicts :sweat: that was messy!

2021-02-23 15:55 UTC, rjd22 commented
@Jean85 @ste93cry Thanks for your work. I've moved the classes to be ordered similar to the other tracing classes.  And added the changes to the Changelog. I think this one is good to go. When this is merged I will start testing this on a acceptance environment to test the stability and report back the results :).

2021-02-25 11:44 UTC, Asesjix commented
Here is a good integration from Jaeger.
You could certainly learn something from the integration.
https://github.com/code-tool/jaeger-client-symfony-bridge

2021-02-27 01:03 UTC, ste93cry commented
>Here is a good integration from Jaeger.
>You could certainly learn something from the integration

Thank you. I'm taking inspiration from the Opentelemetry project because I heard about it in the past, but looking at the package you linked it should be on the same wavelength 😃 

>I've moved the classes to be ordered similar to the other tracing classes.

Thank you for contributing to the project. I had no time to leave a code review before you made more changes, I feel sorry for this, but I moved the classes back to the `EventListener` directory because I think that since they are listeners it's better to have all of them under one place only. Instead, the other are specific pieces of integration for third parties that are well suited to be organized under a different folder structure.

>When this is merged I will start testing this on a acceptance environment to test the stability and report back the results :)

Because as of now I mainly used the tests (both unit and e2e) to simulate requests and console commands to check that at least the basics work, this would be really cool!

2021-02-27 01:09 UTC, ste93cry commented on phpstan.neon
> +        - tests/EventListener/Tracing/RequestListenerTest.php
I changed the code to make this unnecessary, generally speaking the less things we exclude from the analysis the better it is 😃

2021-03-01 08:26 UTC, Jean85 requested changes

2021-03-01 08:26 UTC, Jean85 commented on src/Resources/config/schema/sentry-1.0.xsd
> +            <xsd:element name="request" type="tracing-request" minOccurs="0" maxOccurs="1" />
Does it make sense to enable/disable only the request part? Shouldn't this be enabled always when tracing is enables, since it should provide the basic span?

2021-03-01 08:26 UTC, Jean85 commented on tests/bootstrap.php
> +// mocked methods.
Couldn't we use PHPUnit's `setupBeforeClass` hook? So it would also be localized to the test that needs it.

2021-03-01 09:48 UTC, rjd22 commented on src/Resources/config/schema/sentry-1.0.xsd
> +            <xsd:element name="request" type="tracing-request" minOccurs="0" maxOccurs="1" />
I would say the same. When you enable tracing I would expect symfony base tracing to enable without extra configuration.

2021-03-01 09:51 UTC, rjd22 commented on src/EventListener/TracingRequestListener.php
> +            return substr($protocolVersion, \strlen('HTTP/'));
`substr` is not namespaced and `\strlen` is. Maybe we should make a phpcs check for this. AFAIK. importing them or atleast appending them with `\` saves the compiler some time on the local lookup.

2021-03-01 10:08 UTC, rjd22 commented on composer.json
> +        "symfony/polyfill-php80": "^1.22",
To be honest I don't feel comfortable to add a polyfill as dependency. This is something that changes global behavior of the engine also for the user of the library. Is it really necessary when we can use `strpos`?

2021-03-01 10:19 UTC, stayallive commented on composer.json
> +        "symfony/polyfill-php80": "^1.22",
Unfortunately at this point it doesn't really matter anymore.

> https://github.com/getsentry/sentry-php/blob/51af981636bbe97fe9271dab76819d02593c3191/composer.json#L38

2021-03-01 18:01 UTC, ste93cry commented on tests/bootstrap.php
> +// mocked methods.
It doesn't work because the data providers in PHPUnit are called before the `setupBeforeClass()` method, therefore the classes will be loaded by the autoloader long before the moment we actually need to mock the time-related functions

2021-03-01 18:08 UTC, ste93cry commented on src/EventListener/TracingRequestListener.php
> +            return substr($protocolVersion, \strlen('HTTP/'));
>Maybe we should make a phpcs check for this

Actually, this is the result of applying the [`native_function_invocation`](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.18/doc/rules/function_notation/native_function_invocation.rst) PHPCS rule

>importing them or atleast appending them with `\` saves the compiler some time on the local lookup

Right, but according to the PHP-CS-Fixer documentation only certain functions benefit from this change, and this is why the `@internal` config is the default value for the rule

2021-03-01 18:10 UTC, ste93cry commented on composer.json
> +        "symfony/polyfill-php80": "^1.22",
As said by @stayallive, this doesn't really matter because the polyfill is already required by the main SDK and probably by a lot of other packages as well

>This is something that changes global behavior of the engine also for the user of the library

I don't know what you mean with "changing the global behavior of the engine", but the polyfill only adds functions that are normally available in newer versions of PHP to an older version. There is nothing magic happening here

2021-03-01 18:12 UTC, ste93cry commented on src/Resources/config/schema/sentry-1.0.xsd
> +            <xsd:element name="request" type="tracing-request" minOccurs="0" maxOccurs="1" />
I agree, these were my initial thoughs. However, what if I want to enable tracing for other things but not for the request? Right now, the fact that the request also starts a transaction is just a coincidence

2021-03-02 07:57 UTC, Jean85 commented on src/Resources/config/schema/sentry-1.0.xsd
> +            <xsd:element name="request" type="tracing-request" minOccurs="0" maxOccurs="1" />
Wouldn't the other pieces of tracing break without and underlying new transaction coming from the request?

2021-03-02 17:19 UTC, ste93cry commented on src/Resources/config/schema/sentry-1.0.xsd
> +            <xsd:element name="request" type="tracing-request" minOccurs="0" maxOccurs="1" />
No, because we always check if a transaction or a span is started, but of course nothing will be traced if neither of them exists. I'm not sure how to proceed, but since starting a transaction is strictly connected with the start of a request, probably you're right in saying that it makes no sense to let users disable the listeners in this specific case

2021-03-02 17:42 UTC, rjd22 commented on src/Resources/config/schema/sentry-1.0.xsd
> +            <xsd:element name="request" type="tracing-request" minOccurs="0" maxOccurs="1" />
@ste93cry Imo I would indeed say the ability of disabling the tracers would most likely not needed.

There is always the option to turn the check around so having it always enabled but giving users the option to disable it? So enabled by default.

2021-03-02 17:46 UTC, ste93cry commented on src/Resources/config/schema/sentry-1.0.xsd
> +            <xsd:element name="request" type="tracing-request" minOccurs="0" maxOccurs="1" />
>There is always the option to turn the check around so having it always enabled but giving users the option to disable it? So enabled by default.

Yes, on suggestion of @stayallive this is what I'm going to do in an upcoming PR. I'm leaving the code as-is here because it's consistent with how the rest of the PRs got implemented and because doing this kind of change here would be out-of-scope, considering that I have to change all other listeners as well

2021-03-02 17:48 UTC, rjd22 commented
Btw @ste93cry I've been checking your improvements on my implementation and wanted to thank you personally for how much better this implementation has become.

Thank you!

2021-03-02 17:54 UTC, ste93cry commented
FYI, I reverted some of your changes, for example the one that was creating a span for the response and the controller, because I'm not sure we need to go so deep at this moment with tracing and because I'm not sure the events you used were as precise as we would expect. Since I didn't want to postpone merging this PR for too much time, we can go back to the table and improve these aspects further in the next iterations

2021-03-03 07:52 UTC, Jean85 approved these changes
Great work everybody!

2021-03-03 09:26 UTC, merged