Add global switch to allow disabling all instrumentations for the tracing feature
getsentry/sentry-symfony pull request #467
Opened 2021-03-16 09:38 UTC by Jean85

As suggested by @stayallive in https://github.com/getsentry/sentry-symfony/pull/466#issuecomment-800084751

2021-03-16 09:53 UTC, Jean85 commented
I'm not sure if this needs more tests, otherwise it's ready for review.

2021-03-29 17:23 UTC, ste93cry requested changes

2021-03-29 17:23 UTC, ste93cry commented on tests/DependencyInjection/SentryExtensionTest.php
> +        $this->assertEmpty($container->getParameter('sentry.tracing.dbal.connections'));
A really small change, just for personal pleasure: can you please move this line as last one 🙏?

2021-03-29 17:41 UTC, stayallive approved these changes
If I'm understanding it correctly this seems like a great solution 👌

2021-03-30 17:18 UTC, ste93cry requested changes
@Jean85 you forgot to enable all tracing instrumentations, which we want to do if we want to keep `sentry.tracing.enabled = true` by default. I started this work in #466, so feel free to cherry-pick the commits from there or merge this PR into mine and then I will make the final changes to tie everything together

2021-03-31 07:31 UTC, Jean85 commented
@ste93cry I would prefer not to mix the two PRs to avoid making the review harder. I've switched them on by default, you can go ahead afterward with your PR with just fixing the small conflict.

2021-03-31 07:45 UTC, Jean85 commented
Ok, a full-red CI has shown me why that wasn't a good idea... Let's merge #466 first then, and then we can come back here.

2021-03-31 08:00 UTC, Jean85 commented
Ok, scratch that: I've merged #466 + rebased, I'll address the comments coming from that PR and we should be good to go!

2021-03-31 13:04 UTC, Jean85 reviewed
@ste93cry @stayallive I've merged #466 into this one, you can review it as a whole now.

I've left a few comments to ease the review.

2021-03-31 22:31 UTC, ste93cry requested changes

2021-03-31 22:31 UTC, ste93cry commented on tests/DependencyInjection/Compiler/DbalTracingPassTest.php
> +        $container->setParameter('sentry.tracing.dbal.enabled', true);
This line is repeated twice

2021-03-31 22:31 UTC, ste93cry commented on tests/DependencyInjection/Compiler/DbalTracingPassTest.php
> -        $container->setParameter('doctrine.connections', ['doctrine.dbal.foo_connection', 'doctrine.dbal.bar_connection', 'doctrine.dbal.baz_connection']);
I'm not sure this is a good idea because this way all tests will share the same connections and the same container parameters, but not all tests need them at all or need them configured in a particular way. My fear is that in the future we may get into the trap that we cannot evolve the test methods independently as easy as of now

2021-03-31 22:31 UTC, ste93cry commented on tests/DependencyInjection/Compiler/DbalTracingPassTest.php
> +        $connection3 = (new Definition(Connection::class))->setPublic(true);
Why you added a third connection?

2021-03-31 22:31 UTC, ste93cry commented on tests/DependencyInjection/Compiler/DbalTracingPassTest.php
> +        $container = $this->createContainerBuilder();
After these changes, this test case is the same as the first one of the data provider. Did you meant to test `sentry.tracing.enabled` in one of them?

2021-03-31 22:31 UTC, ste93cry commented on tests/DependencyInjection/Compiler/DbalTracingPassTest.php
>          $container->setParameter('sentry.tracing.dbal.connections', ['foo', 'bar', 'baz', 'qux']);
Yes, correct, if no connection exists with that name we will simply skip it. Maybe we should be more strict in this regards?

2021-03-31 22:31 UTC, ste93cry commented on tests/DependencyInjection/Compiler/DbalTracingPassTest.php
> -        $container->setParameter('doctrine.connections', ['doctrine.dbal.foo_connection', 'doctrine.dbal.bar_connection', 'doctrine.dbal.baz_connection']);
I'm not sure this is a good idea because this way all tests will share the same connections and the same container parameters, but not all tests need them at all or need them configured in a particular way. My fear is that in the future we may get into the trap that we cannot evolve the test methods independently as easy as of now

2021-04-01 06:57 UTC, Jean85 commented on tests/DependencyInjection/Compiler/DbalTracingPassTest.php
> +        $connection3 = (new Definition(Connection::class))->setPublic(true);
Because by default now we have 3 connections in the container, and the test would otherwise fail.

2021-04-01 06:58 UTC, Jean85 commented on tests/DependencyInjection/Compiler/DbalTracingPassTest.php
> +        $container = $this->createContainerBuilder();
Yes, exactly. My mistake, I changed the first one.

2021-04-01 16:26 UTC, Jean85 commented on tests/DependencyInjection/Compiler/DbalTracingPassTest.php
>          $container->setParameter('sentry.tracing.dbal.connections', ['foo', 'bar', 'baz', 'qux']);
That would probably be good, since it would blow up on cache clear, not in prod :+1:

2021-04-01 16:33 UTC, ste93cry commented on tests/DependencyInjection/Compiler/DbalTracingPassTest.php
> -        $container->setParameter('doctrine.connections', ['doctrine.dbal.foo_connection', 'doctrine.dbal.bar_connection', 'doctrine.dbal.baz_connection']);
As discussed on Discord, let's leave this as-is and postpone any change to the moment we will need them

2021-04-01 16:46 UTC, ste93cry approved these changes

2021-04-01 16:46 UTC, merged