Unwrap HandlerFailedException for sync Messenger messages too
getsentry/sentry-symfony pull request #475
Opened 2021-04-01 11:32 UTC by Jean85

Will fix #469

2021-04-01 15:43 UTC, Ocramius approved these changes
**assuming** (needs to be checked by maintainers) that `HandlerFailedException` can be un-wrapped by default within the context of `ErrorListener#handleExceptionEvent()`, I'm totally for this patch :+1:

2021-04-01 15:59 UTC, Jean85 commented
IMO it should, because it can also contain multiple exceptions, due to multiple handlers for the same message, failing together.

2021-04-01 16:17 UTC, ste93cry requested changes
Build is broken 😬

2021-04-01 16:17 UTC, ste93cry commented on tests/End2End/App/Controller/MessengerController.php
> +        $this->messenger->dispatch(new SyncMessage(false));
The constructor of the `SyncMessage` class does not accept any parameter, not sure why PHPStan does not complain here

2021-04-01 16:17 UTC, ste93cry commented on tests/End2End/App/Messenger/IgnorableException.php
> +class IgnorableException extends \Exception
Class can be made `final`

2021-04-01 16:17 UTC, ste93cry commented on tests/End2End/App/Messenger/SyncMessage.php
> +class SyncMessage
Class can be made `final`

2021-04-01 16:17 UTC, ste93cry commented on tests/End2End/App/Messenger/SyncMessageHandler.php
> +class SyncMessageHandler implements MessageHandlerInterface
Class can be made `final`

2021-04-02 06:16 UTC, Jean85 commented
CI failure seems triggered by https://github.com/symfony/symfony/issues/40677

If we cannot fix it, we can (temporarily?) switch to `pcov` for coverage collection?

2021-04-02 12:59 UTC, Ocramius commented
@Jean85 IMO using `pcov` is more reliable, if this stuff is only used for coverage.

2021-04-02 14:46 UTC, Ocramius commented
```

Failed asserting that actual size 2 matches expected size 1.

/home/runner/work/sentry-symfony/sentry-symfony/tests/End2End/End2EndTest.php:258
/home/runner/work/sentry-symfony/sentry-symfony/tests/End2End/End2EndTest.php:157
```

I wonder if that's because the messenger encounters the fatal error twice?

2021-04-02 15:24 UTC, Jean85 commented
Why would encounter it twice?

Also, tests do NOT fail locally, there's definitely something wonky here..

2021-04-02 15:38 UTC, Ocramius commented
The code around the assertions looks completely wonky:

https://github.com/getsentry/sentry-symfony/blob/43cd505db0a9e370326226467a8a61c7c7deb52f/tests/End2End/End2EndTest.php#L141-L155

The `} catch {` block should not exist there, should it?

2021-04-02 15:46 UTC, Jean85 commented
IIRC that was done in #322 due to the fact that with different Symfony version you would get different behaviours..

Let's see what happens if I revert that.

2022-01-19 21:46 UTC, closed without merging