Add distributed tracing support for the Symfony Cache component
getsentry/sentry-symfony pull request #477
Opened 2021-04-04 16:11 UTC by ste93cry

Here we go with another instrumentation, this time for the [Cache](https://symfony.com/doc/current/components/cache.html) component. Its implementation is quite simple, and it resembles the one of the DBAL.

2021-04-06 10:38 UTC, Jean85 requested changes

2021-04-06 10:38 UTC, Jean85 commented on CHANGELOG.md
> -- Added missing `capture-soft-fails` config schema option (#417)
Is this removal intentional or has it been lost during rebase?

2021-04-06 10:38 UTC, Jean85 commented on tests/DependencyInjection/ConfigurationTest.php
> +                    'enabled' => interface_exists(CacheInterface::class),
This needs to be added to the `full` configuration fixture.

2021-04-06 11:22 UTC, ste93cry commented on CHANGELOG.md
> -- Added missing `capture-soft-fails` config schema option (#417)
It's a duplicate entry (fix has been released in `4.0.1`), probably the result of a bad merge between `master` and `develop`

2021-04-06 11:44 UTC, ste93cry commented on tests/DependencyInjection/ConfigurationTest.php
> +                    'enabled' => interface_exists(CacheInterface::class),
Does it makes sense? Unlike the other instrumentations, this one does not register any service by default so there is nothing to test, apart from the compiler pass

2021-04-06 14:22 UTC, Jean85 commented on tests/DependencyInjection/ConfigurationTest.php
> +                    'enabled' => interface_exists(CacheInterface::class),
Services get still decorated; so it makes sense to test that somehow in end2end.

2021-04-06 18:04 UTC, ste93cry commented on tests/DependencyInjection/ConfigurationTest.php
> +                    'enabled' => interface_exists(CacheInterface::class),
The decoration is tested in the `CompilerPassTest` class, it's kinda of an integration test as it really uses the `ContainerBuilder` to execute all steps 😉 The only thing that is mocked is the service definition of the abstract services

2021-04-06 20:46 UTC, Jean85 approved these changes

2021-04-12 07:59 UTC, Jean85 commented
Build should be fixed by #480

2021-04-12 13:39 UTC, merged

2021-04-23 15:09 UTC, VincentLanglet commented
Hi @ste93cry  Could some documentation of this option be added in the Readme ?
I don't understand what it does.

2021-04-23 15:58 UTC, ste93cry commented
Please open an issue in [`getsentry/sentry-docs`](https://github.com/getsentry/sentry-docs), documentation indeed needs some updating

2021-04-25 20:29 UTC, VincentLanglet commented
Done https://github.com/getsentry/sentry-docs/issues/3463