Allow to pass custom serializer and representation_serializer in configuration
getsentry/sentry-symfony pull request #491
Opened 2021-04-28 09:54 UTC by olsavmic

Follow up on https://github.com/getsentry/sentry-symfony/issues/482

> Well I can improve the docs but I would say that such compiler pass is rather a hack than proper solution.
> The problem with the compiler pass is that it's a modification of the internals and not the public API so it's a subject to change in future releases without any warning.
>I know of SerializableInterface and class_serializers but there are use cases when you need to modify "global" behaviour.
> I'd prefer to add the representation serializer (and perhaps even the serializer) as optional configuration options.
>I can prepare a PR if such modification is a welcome change.

2021-04-28 09:58 UTC, olsavmic commented
Custom serializer can then be registered as a service as usually

```yaml
App\Logger\SentryReprSerializer:
    arguments:
        $options: '@sentry.client.options'
```

2021-05-14 10:45 UTC, olsavmic commented
@Jean85 @ste93cry I did not receive any comment on this issue. Can I ask for a review of this PR or a comment on the related issue so we can proceed or close the issue? 

Thanks a lot!

2021-05-14 12:58 UTC, Jean85 requested changes
Code looks fine for what I can see. It would require a changelog entry though.
Also, I'll retarget do `develop` since it's a new feature.

@ste93cry WDYT? Is this a valuable feature in your opinion?

2021-05-14 22:17 UTC, ste93cry requested changes
>Is this a valuable feature in your opinion?

Yes, it is. In the future though I would like to see both serializers gone and replaced with either a refactored version or a third party lib so that we don't have to maintain the mess they are right now

2021-05-14 22:17 UTC, ste93cry commented on tests/DependencyInjection/SentryExtensionTest.php
> +        $setSerializerCalls = array_filter(
Can you please use `assertDefinitionMethodCallAt` rather than this code? Your version is more future-proof, but I prefer to keep the consistency with the other tests until we decide to refactor the assertion helper

2021-05-14 22:17 UTC, ste93cry commented on tests/DependencyInjection/SentryExtensionTest.php
> +        $setSerializerCalls = array_filter(
Can you please use `assertDefinitionMethodCallAt` rather than this code? Your version is more future-proof, but I prefer to keep the consistency with the other tests until we decide to refactor the assertion helper

2021-05-14 22:17 UTC, ste93cry commented on tests/DependencyInjection/SentryExtensionTest.php
> +    public function testCustomSerializer(): void
Please rename this method to `testSerializerOption`

2021-05-14 22:17 UTC, ste93cry commented on tests/DependencyInjection/SentryExtensionTest.php
> +    public function testRepresentationSerializer(): void
Please rename this method to `testRepresentationSerializerOption`

2021-05-20 16:34 UTC, ste93cry commented
Stricly speaking about the current PR's code I have nothing more to say besides great work, however I'm now wondering if this is the best way to tackle this problem. The fact is that the serializer requires the options of the client whose service is not defined until it gets created by the `SentryExtension` during the compilation phase of the container. In turn, when I coded the service of the options I made it `private` because my though was (and is) that to access them you should pass from the client: the options is not something meant to be injected as a normal service because it belongs to a specific client instance. Maybe, instead of allowing to set the serializer instance, we should instead use a factory that given the options returns an instance of the serializer, forcibly making people aware that each client must have its own serializer instance (which usually doesn't happen)?

2022-01-19 21:46 UTC, closed without merging