Add bus, receiver and message name to extra's
getsentry/sentry-symfony pull request #492
Opened 2021-04-28 14:55 UTC by airoude

Hello,

With this PR we can send extra information about the worker like busName, receiver, and the actual message object name.
In the future (when I have more time) we can add configure custom stamps to be sent along.

Since I couldn't mock the Scope object because it is marked final, no assertions were made against those.

2021-04-28 19:26 UTC, ste93cry requested changes
Can you please also add a CHANGELOG entry following the pattern of the existing entries?

2021-04-28 19:26 UTC, ste93cry commented on tests/EventListener/MessengerListenerTest.php
> +            ->method('withScope');
Since `withScope` is basically a wrapper that just calls the given callback by providing it a new scope, you can simulate this behaviour using something like the code below (untested) and asserting that the data is correctly set

```php
->method('withScope')
->willReturnCallback(static function (callable $callback) use ($scope): void {
    $callback($scope);

    $this->assertSame(...,);
});
```

2021-04-28 19:26 UTC, ste93cry commented on tests/EventListener/MessengerListenerTest.php
> +        $event = new WorkerMessageHandledEvent(
Instead of editing this test case I suggest to add a new one. The reason is that we should ensure that the code works both when the `stamp` is present and when it isn't. In this specific case, unlike the other reviewed places, we should also add the data provider

2021-04-28 19:51 UTC, airoude commented on src/EventListener/MessengerListener.php
> +        $this->hub->captureException($exception);
I couldn't find any examples where ```withScope```  was used in combination with ```captureException```. If I put it inside the ```withScope``` it doesn't get invoked. Any tips?

2021-04-28 19:54 UTC, airoude commented on src/EventListener/MessengerListener.php
> +            if ($messageBusStamp = $envelope->last(BusNameStamp::class)) {
Hm, why? This already checks on null.

2021-04-28 19:56 UTC, airoude commented on src/EventListener/MessengerListener.php
> +                assert($messageBusStamp instanceof BusNameStamp);
The assert gives type-hinting and it validates.

2021-04-28 19:56 UTC, airoude commented on src/EventListener/MessengerListener.php
> +                $scope->setTag('messenger.message_bus', $messageBusStamp->getBusName());
Yes valid point.

2021-04-28 20:00 UTC, ste93cry commented on src/EventListener/MessengerListener.php
> +            if ($messageBusStamp = $envelope->last(BusNameStamp::class)) {
I prefer to be explicit and I think it makes more clear the intent of what is happening here for the reader

2021-04-28 20:07 UTC, airoude commented on tests/EventListener/MessengerListenerTest.php
> +            ->method('withScope');
Where is the ```$scope``` coming from?

2021-04-28 20:16 UTC, ste93cry commented on src/EventListener/MessengerListener.php
> +                assert($messageBusStamp instanceof BusNameStamp);
Quoting from the official PHP documentation, their use should be mainly reserved as a debugging feature. In this context, I don't think it's the case: we trust the vendor to return an instance of the object expected, otherwise there would be a bug there. I think that an annotation is more than enough, even if we lose the so called "validation"...

2021-04-28 20:19 UTC, airoude commented on src/EventListener/MessengerListener.php
> +            if ($messageBusStamp = $envelope->last(BusNameStamp::class)) {
This pattern is broadly used in Symfony, Doctrine, and Composer. But I will make it explicit.

2021-04-28 20:26 UTC, ste93cry commented on tests/EventListener/MessengerListenerTest.php
> +            ->method('withScope');
Oh sorry, I partially copy-pasted the code from some other place of the codebase. In this case, `$scope` can be instantiated outside the lambda (and consequently the assertions too can be moved to the outside if you prefer) or you can initialize the variable inside the lambda and avoid passing it from the outside. It's your call

2021-04-28 20:36 UTC, airoude commented on tests/EventListener/MessengerListenerTest.php
> +            ->method('withScope');
Thanks!

2021-04-28 21:59 UTC, airoude commented on tests/EventListener/MessengerListenerTest.php
> +            ->method('captureEvent');
Idk why this one fails. @ste93cry could you help?

2021-04-29 18:44 UTC, ste93cry commented on tests/EventListener/MessengerListenerTest.php
> +            ->method('captureEvent');
It's failing because you are not mocking the `withScope()` method, therefore the callback function is never invoked

2021-04-29 20:48 UTC, airoude commented on tests/EventListener/MessengerListenerTest.php
> +            ->method('captureEvent');
Isn't it mocked on L106?

2021-04-29 21:19 UTC, ste93cry commented on tests/EventListener/MessengerListenerTest.php
> +            ->method('captureEvent');
Yes, but this line is referring to the `testHandleWorkerMessageFailedEventWithStamps()` test method, while the failing one is `testHandleWorkerMessageFailedEvent()`

2021-04-29 21:50 UTC, airoude commented on tests/EventListener/MessengerListenerTest.php
> +            ->method('captureEvent');
Oh jeez.. a long week. Thanks for the catch!

2021-05-11 19:23 UTC, ste93cry requested changes
I see there is still some commented code [here and there](https://github.com/getsentry/sentry-symfony/pull/492/files#diff-188d24189ff68e40532a471f178a0824ab89645b1c0bb35e3e3e8dcbc30d9858R120), and I don't understand why you switched from `captureException()` to `captureEvent()`. I mentioned the latter in https://github.com/getsentry/sentry-symfony/pull/492#discussion_r622498062 just for the sake of the example, I didn't mean you to change it

2021-05-11 19:23 UTC, ste93cry commented on CHANGELOG.md
> +- Attach bus, receiver and message class name as extra's
Please add a reference to this PR

2021-05-11 19:23 UTC, ste93cry commented on src/EventListener/MessengerListener.php
> +        $exceptionHint = EventHint::fromArray([
I don't understand why you are manually creating the event here, `captureException()` was fine as it was and using `captureEvent()` does not have any benefit here apart from making the code unnecessarily more complicated

2021-05-11 19:23 UTC, ste93cry commented on tests/EventListener/MessengerListenerTest.php
> +                // 'messenger.message_bus' => 'commandBus',
While it's true that the scope has no getters, you should call `$scope->applyToEvent(Event::createEvent())` and then check that the data is set on the event itself

2021-07-24 23:01 UTC, ste93cry commented
I took the time to finish this PR as I would really love to see it merged. Hopefully you don't mind I rebased the PR and pushed changes to your code. It would be great if you could test it out before I give the final approval to be sure everything works as expected

2021-07-27 07:36 UTC, Jean85 approved these changes

2021-07-28 19:49 UTC, ste93cry approved these changes
Since all is silent, LGTM 🚢 Thanks @airoude for the work you did

2021-07-28 19:50 UTC, merged