Add the `sentry_trace_meta()` Twig function to print the `sentry-trace` HTML meta tag
getsentry/sentry-symfony pull request #510
Opened 2021-05-19 11:55 UTC by ste93cry

As per title, fixes #458 by adding the `sentry_trace_meta()` Twig function. Unlike the Laravel's SDK, I decided to always print the HTML meta tag regardless of whether a transaction/span is active because I like to be consistent in the expected output and because there should be no issue in having a blank string as its content

2021-05-19 16:03 UTC, Jean85 requested changes

2021-05-19 16:03 UTC, Jean85 commented on src/Twig/SentryExtension.php
> +        return sprintf('<meta name="sentry-trace" content="%s" />', null !== $span ? $span->toTraceparent() : '');
I know it's a nitpick, but I had to double take because it seemed "transparent" :sweat_smile: 
```suggestion
        return sprintf('<meta name="sentry-trace" content="%s" />', null !== $span ? $span->toTraceParent() : '');
```

2021-05-19 16:28 UTC, ste93cry commented on src/Twig/SentryExtension.php
> +        return sprintf('<meta name="sentry-trace" content="%s" />', null !== $span ? $span->toTraceparent() : '');
Although in PHP the function names are case-insensitive, I think it's an error to call them with another casing

2021-05-20 19:30 UTC, Jean85 commented on src/Twig/SentryExtension.php
> +        return sprintf('<meta name="sentry-trace" content="%s" />', null !== $span ? $span->toTraceparent() : '');
Ok, so I think we should fix this with a PR, it's not a BC.

2021-05-20 19:30 UTC, Jean85 approved these changes

2021-05-20 19:30 UTC, merged