Rework DBAL compat layer
getsentry/sentry-symfony pull request #512
Opened 2021-05-27 16:14 UTC by Jean85

WIP

@ste93cry WDYT of this different approach?

2021-05-27 22:49 UTC, ste93cry requested changes
I think that by making `2.13` the minimum required version (they recently added back support for PHP 7.2) we could probably cleanup some other code because they added a forward compatibility layer

2021-05-27 22:49 UTC, ste93cry commented on tests/Tracing/Doctrine/DBAL/TracingDriverTest.php
> +class MockDriver implements DriverInterface
It's not clear to me why you added this class instead of mocking the interface like I was doing before. What's the benefit of doing this or the blocker that makes it impossible now to do it?

2021-05-28 08:13 UTC, Jean85 commented on tests/Tracing/Doctrine/DBAL/TracingDriverTest.php
> +class MockDriver implements DriverInterface
Psalm was complaining. But it didn't fix the issue anyway, so we could rollback this.

Would bumping DBAL requirement create issues?

2021-05-28 08:19 UTC, ste93cry commented on tests/Tracing/Doctrine/DBAL/TracingDriverTest.php
> +class MockDriver implements DriverInterface
>Would bumping DBAL requirement create issues?

I don't think so, but the best thing is to try. We couldn't bump the minimum version before simply because there was no support for PHP 7.2, which is now back

2021-06-01 07:55 UTC, Jean85 commented on tests/Tracing/Doctrine/DBAL/TracingDriverTest.php
> +class MockDriver implements DriverInterface
I've investigated it further. The only additional FC is https://github.com/doctrine/dbal/pull/4529, which is about `ResultStatement`, that we do not touch, so I don't see any advantages.

I'll try to push this PR forward, and on the code side it seems to work, but the static analysis is a complete mess.

2021-06-24 13:53 UTC, tacman commented on tests/Tracing/Doctrine/DBAL/TracingDriverTest.php
> +class MockDriver implements DriverInterface
>> there was no support for PHP 7.2, which is now back

But isn't 7.2 dead?

2021-06-24 14:00 UTC, ste93cry commented on tests/Tracing/Doctrine/DBAL/TracingDriverTest.php
> +class MockDriver implements DriverInterface
It's EOL, but we still support it mainly because Sentry must run also on legacy platforms, if possible

2021-07-07 21:46 UTC, Jean85 commented
Closing in favor of #527

2021-07-07 21:46 UTC, closed without merging