Improve end to end tests
getsentry/sentry-symfony pull request #517
Opened 2021-06-01 16:11 UTC by Jean85

2021-07-03 21:08 UTC, ste93cry requested changes

2021-07-06 07:36 UTC, Jean85 commented on tests/End2End/End2EndTest.php
> +    /** @phpstan-ignore-next-line */
I fixed it altogether.

2021-07-06 07:37 UTC, Jean85 commented on tests/End2End/App/deprecations_for_5.yml
> +    utf8: true
Nope, it's missing in 3.4

2021-07-07 18:28 UTC, ste93cry approved these changes

2021-07-07 18:31 UTC, merged