Fix decoration of cache adapters inheriting parent service
getsentry/sentry-symfony pull request #525
Opened 2021-06-16 21:00 UTC by ste93cry

Fixes #524: when running a compiler pass during the `TYPE_BEFORE_OPTIMIZATION` phase, services inheriting a parent one have not been resolved yet and consequently their class is still set to `null`. This was causing the check to decorate the cache adapter according to whether they were implementations of the `TagAwareAdapterInterface` interface or not to fail, resulting in the decorator to always inherit the base `AdapterInterface` interface even when the adaptor should have been an instance of `TagAwareAdapterInterface`

2021-06-17 06:44 UTC, Jean85 requested changes

2021-06-17 06:44 UTC, Jean85 commented on src/DependencyInjection/Compiler/CacheTracingPass.php
> +            $class = $class ?: $definition->getClass();
This loop doesn't seem correct to me... If `$class` is populated at first try, it basically ignores the previous line.

Maybe we can rewrite this in a more understandable way?

2021-06-17 06:44 UTC, Jean85 commented on src/DependencyInjection/Compiler/CacheTracingPass.php
> +                continue;
How is it possible that this line is never covered? Shouldn't the method "explode" if it can't find a FQCN for the service?

2021-06-17 07:48 UTC, ste93cry commented on src/DependencyInjection/Compiler/CacheTracingPass.php
> +                continue;
The `resolveDefinitionClass()` method can return `null`, and in this case instead of throwing an exception I decided to just skip decorating the service. The container compilation will do the rest anyway

2021-06-18 10:23 UTC, Jean85 approved these changes

2021-06-18 10:23 UTC, merged