Bump DBAL support to 2.13+
getsentry/sentry-symfony pull request #527
Opened 2021-06-23 13:26 UTC by Jean85

WIP

This is an alternative to #512, with a complete different approach as suggested in https://github.com/getsentry/sentry-symfony/pull/512#pullrequestreview-670685888

This should also fix #483 as a side effect.

2021-07-08 22:14 UTC, ste93cry requested changes

2021-07-08 22:14 UTC, ste93cry commented on src/Tracing/Doctrine/DBAL/TracingDriver.php
> +use Doctrine\DBAL\Driver as DBALDriver;
Why not aliasing the interface? I did it mainly to keep consistency with our standard which is to have the `Interface` suffix, but if we don't want to alias this interface anymore then we should also not create aliases for the one that came below

2021-07-08 22:14 UTC, ste93cry commented on src/Tracing/Doctrine/DBAL/TracingDriver.php
> + * This implementation IS cross-compatible with both DBAL 2 and 3 thanks to
This part of the documentation was more a warning that a simple note, and should stay the same because this class still implements things that got removed in DBAL `3.0`, but that are needed for implementations compatible with the `2.x` series

2021-07-08 22:14 UTC, ste93cry commented on tests/Tracing/Doctrine/DBAL/TracingDriverTest.php
> +        /** @phpstan-ignore-next-line */
Maybe it makes sense to extract all errors to the PHPStan baseline to avoid cluttering the code with all these annotations?

2021-07-08 22:14 UTC, ste93cry commented on tests/Tracing/Doctrine/DBAL/TracingDriverTest.php
> +if (interface_exists(DriverInterface::class)) {
I don't get why you moved all the stubs declarations inside this conditional, which is always `true` as long as the DBAL is installed 🤔

2021-07-09 09:48 UTC, Jean85 commented on src/DependencyInjection/Compiler/DbalTracingPass.php
> +            throw new \RuntimeException(sprintf('The Doctrine "%s" interface is missing, DBAL connection cannot be instrumented; check that you have DBAL 2.13+ installed', Driver::class));
You're right. This works by accident in CI due to the fact we `require-dev` `doctrine/dbal ^2.13`.
We should check for `\Doctrine\DBAL\Result`, which was introduced in 2.13.0 with https://github.com/doctrine/dbal/pull/4529/files#diff-ba0bc531c4d594368d24a7fea2d81f1aff2841ccf658fa2e4b51b9c822abb6d9R20

2021-07-09 09:51 UTC, Jean85 commented on src/Tracing/Doctrine/DBAL/TracingDriver.php
> +use Doctrine\DBAL\Driver as DBALDriver;
Reverted back.

2021-07-09 09:53 UTC, Jean85 commented on tests/Tracing/Doctrine/DBAL/TracingDriverTest.php
> +if (interface_exists(DriverInterface::class)) {
Because we have a CI job without DBAL installed; in that case, the test would explode due to missing classes.

2021-07-25 18:56 UTC, ste93cry requested changes

2021-07-25 18:56 UTC, ste93cry commented on src/DependencyInjection/Compiler/DbalTracingPass.php
> +            throw new \RuntimeException(sprintf('The Doctrine "%s" interface is missing, DBAL connection cannot be instrumented; check that you have DBAL installed', Driver::class));
I suggest to change the thrown exception to `LogicException` and the message to `Tracing support cannot be enabled as the Doctrine DBAL 2.13+ package is not installed. Try running "composer require doctrine/dbal:^2.13".` to be consistent with what Symfony does for its own components. Furthermore, we can refactorize this method to throw the exception just once at the end of the function when neither the `Doctrine\DBAL\Result` interface nor the class with the same name exist

2021-07-25 18:56 UTC, ste93cry commented on tests/Tracing/Doctrine/DBAL/TracingDriverTest.php
> +if (interface_exists(DriverInterface::class)) {
How can it explode if the declaration of the stubs was already wrapped inside an `interface_exists()` statement?

2021-07-27 11:02 UTC, Jean85 commented on tests/Tracing/Doctrine/DBAL/TracingDriverTest.php
> +if (interface_exists(DriverInterface::class)) {
I think there was a version where that check was failing.

2021-07-28 19:39 UTC, ste93cry requested changes
Two small nitpicks and then LGTM for me

2021-07-28 19:39 UTC, ste93cry commented on src/DependencyInjection/Compiler/DbalTracingPass.php
> +     * @throws \RuntimeException
This DocBlock is incorrect now that we've changed to throwing a `LogicException`. Anyway, I wonder if it makes sense to leave it because it provide little value considering that the method is not part of a public API and therefore users cannot benefit from it

2021-07-28 19:39 UTC, ste93cry commented on src/DependencyInjection/Compiler/DbalTracingPass.php
> +        if (interface_exists(Driver::class)) {
I think we are safe in removing this condition because the nested statements works on their own

2021-07-29 12:23 UTC, ste93cry approved these changes

2021-07-29 12:25 UTC, merged