Pass logger from options to TransportFactory
getsentry/sentry-symfony pull request #555
Opened 2021-09-13 11:08 UTC by simPod

I have noticed that a transport error was being logged in https://github.com/getsentry/sentry-php/blob/bfab90c7ef921221b52b75b5108201e87f0f4661/src/Transport/HttpTransport.php#L112-L115

but there always was default NullLogger registered. So I've found that even though I set logger via `options` it was no being passed to the Transport.

This fixes it.

2021-09-13 18:02 UTC, ste93cry requested changes

2021-09-13 18:46 UTC, simPod commented on tests/DependencyInjection/SentryExtensionTest.php
> +        $this->assertSame('app.logger', $logger->__toString());
Do you want to magically cast it? It's hard for SA to understand and detects bug.

This guy is right actually https://github.com/ShittySoft/symfony-live-berlin-2018-doctrine-tutorial/pull/3#issuecomment-460441229

2021-09-13 18:49 UTC, simPod commented on src/DependencyInjection/SentryExtension.php
> +        $factoryBuilderDefinition = (new Definition(TransportFactory::class))
I'll try tomorrow but not sure if it's possible as I'm not very familiar with SF DI configuration. `$config['logger']` is optional so not sure if I'll be able to pass it.

2021-09-13 20:23 UTC, ste93cry commented on src/DependencyInjection/SentryExtension.php
> +        $factoryBuilderDefinition = (new Definition(TransportFactory::class))
I think that something along the lines of this should work:

```php
$factoryBuilderDefinition  = $this->getDefinition(TransportFactoryInterface::class);
$factoryBuilderDefinition->setArgument('$logger', ...);
```

2021-09-13 20:31 UTC, ste93cry commented on tests/DependencyInjection/SentryExtensionTest.php
> +        $this->assertSame('app.logger', $logger->__toString());
Makes sense, I'm used to the cast but no strong opinion on leaving this as is, it was mainly for a matter of consistency with other points in the code where we do the same and because I don't really like to call a magic method manually

2021-09-14 19:35 UTC, ste93cry requested changes
Would you mind updating the CHANGELOG too to reference this PR?

2021-09-14 19:35 UTC, ste93cry commented on src/DependencyInjection/SentryExtension.php
> +use function class_exists;
I don't know why PHPCS didn't report this, maybe it's configured to not warn if importing functions, but usually we don't do it. :pray: revert these changes back

2021-09-14 19:35 UTC, ste93cry commented on src/DependencyInjection/SentryExtension.php
> +        $factoryBuilderDefinition->setArgument('$httpClient', null);
What's the reason for also setting this argument explicitly?

2021-09-14 19:35 UTC, ste93cry commented on tests/DependencyInjection/SentryExtensionTest.php
> +        $this->assertSame('app.logger', $logger->__toString());
Can you please still add the blank line before the assertion 🙏 to make the code a little more readable at first sight?

2021-09-14 20:37 UTC, simPod commented on src/DependencyInjection/SentryExtension.php
> +        $factoryBuilderDefinition->setArgument('$httpClient', null);
Symfony tells me to do so: Cannot set sixth without setting fifth

2021-09-14 20:41 UTC, ste93cry commented on src/DependencyInjection/SentryExtension.php
> +        $factoryBuilderDefinition->setArgument('$httpClient', null);
Makes sense, but then I think that as it's done in some parts of Symfony itself it would be better to declare all arguments in the XML config and then override here the last one. WDYT?

2021-09-14 20:41 UTC, simPod commented on src/DependencyInjection/SentryExtension.php
> +use function class_exists;
there's cs fixer, not phpcs. I use phpcs where it's configurable, not sure about fixer 🤷🏾‍♀️

2021-09-14 20:48 UTC, simPod commented on src/DependencyInjection/SentryExtension.php
> +        $factoryBuilderDefinition->setArgument('$httpClient', null);
smart "hack"

2021-09-14 20:59 UTC, simPod commented
ah cahngelog

2021-09-14 21:50 UTC, ste93cry commented on src/DependencyInjection/SentryExtension.php
> +        $factoryBuilderDefinition->setArgument('$httpClient', null);
By setting the `$httpClient` argument to a service, the behaviour of the existing applications may change if that service exists because it may be different from the one that was returned while autodiscovering the HTTP client. To be safe, this should work as expected:

```xml
<service id="Sentry\Transport\TransportFactoryInterface" class="Sentry\SentryBundle\Transport\TransportFactory">
    ...
    <argument>null</argument>
    <argument /> <!-- $logger -->
</service>
```

2021-09-14 21:52 UTC, simPod commented on src/DependencyInjection/SentryExtension.php
> +        $factoryBuilderDefinition->setArgument('$httpClient', null);
aight, i'm no symfony expert so I went with what you've suggested

2021-09-14 21:59 UTC, ste93cry approved these changes
Everything looks good, thank you for the contribution 💪

2021-09-14 22:06 UTC, merged