maintenance/add-type-hin-in-sentry-extension
getsentry/sentry-symfony pull request #563
Opened 2021-10-04 11:50 UTC by eerison

2021-10-04 14:26 UTC, Jean85 requested changes
Thank you for your contribution!

I tried to get them to pop up using the ErrorHandler component but it didn't mark anything, so thank you for spotting it!

Can you add a changelog entry too please?

2021-10-04 15:37 UTC, eerison commented
> Thank you for your contribution!
> 
> I tried to get them to pop up using the ErrorHandler component but it didn't mark anything, so thank you for spotting it!
> 
> Can you add a changelog entry too please?

Hi @Jean85 I added the `changelog` could you check again please :)

2021-10-04 15:48 UTC, Jean85 requested changes

2021-10-04 15:48 UTC, Jean85 commented on CHANGELOG.md
> +- Add typehint to `SentryExtension` dependency injection (Symfony 5.4).
```suggestion
- Add return typehints to `SentryExtension` dependency injection to prepare for Symfony 6. (#563)
```

2021-10-04 17:16 UTC, ste93cry requested changes

2021-10-04 17:16 UTC, ste93cry commented on CHANGELOG.md
> +- Add return typehints to `SentryExtension` dependency injection to prepare for Symfony 6. (#563)
```suggestion
- Add return typehints to the methods of the `SentryExtension` class to prepare for Symfony 6 (#563)
```

2021-10-04 17:19 UTC, ste93cry approved these changes
Thank you!

2021-10-05 07:38 UTC, Jean85 approved these changes

2021-10-05 07:38 UTC, merged