TraceableCacheAdapter compatible with Symfony\Component\Cache\Adapter…
getsentry/sentry-symfony pull request #577
Opened 2021-11-30 12:13 UTC by jaras2678

Issuse https://github.com/getsentry/sentry-symfony/issues/576

2021-11-30 17:33 UTC, ste93cry commented
This change is a breaking change. Moreover, it doesn't work on PHP 7 because the `mixed` typehint was introduced in version 8. There's already an open PR to support Symfony 6, I will find a way to integrate this change there

2021-12-01 09:42 UTC, Jean85 requested changes
Also, please add a changelog entry. I would also require a test, but I would expect this to land from #566. @ste93cry can you check on this?

2021-12-01 09:42 UTC, Jean85 commented on src/Tracing/Cache/TraceableCacheAdapterTrait.php
> +    public function getItem(mixed $key): CacheItem
The variance rules are reversed for arguments, so just by doing this we should be fine:
```suggestion
    public function getItem($key): CacheItem
```

2021-12-01 09:44 UTC, ste93cry commented
@Jean85 there's no need to do anything here, as I said before there's already an open PR to support Symfony 6, with this change included

2021-12-01 09:44 UTC, closed without merging