Fix deprecation: PDOStatement::bindParam(): Passing null to $maxLength
getsentry/sentry-symfony pull request #586
Opened 2021-12-23 10:06 UTC by Jeroeny

`Deprecated: PDOStatement::bindParam(): Passing null to parameter #4 ($maxLength) of type int is deprecated in ./vendor/doctrine/dbal/src/Driver/PDO/Statement.php on line 83`

While it may seem that the deprecation is caused by that Doctrine `Statement` class, it is in fact caused by passing `$length` as `null` to that method which is then passed on the the `PDOStatement` method call. The fix is done the same way as in Doctrine: https://github.com/doctrine/dbal/blob/3.2.x/src/Driver/PDO/Statement.php#L83

2021-12-23 13:51 UTC, Jean85 requested changes
Code looks fine, can you please add a test and a changelog entry?

2021-12-27 13:39 UTC, Jeroeny commented
@Jean85 I've added a test and changelog line. I couldn't just use a `willReturnCallback`, because phpunit always passed the variable explicitly as `null`.

2021-12-27 22:19 UTC, Jean85 requested changes

2021-12-27 22:19 UTC, Jean85 commented on tests/Tracing/Doctrine/DBAL/TracingStatementForV3Test.php
> +     * @var array|null
```suggestion
     * @var mixed[]|null
```

2021-12-27 22:19 UTC, Jean85 commented on tests/Tracing/Doctrine/DBAL/TracingStatementForV3Test.php
> +        $this->assertCount(3, $this->decoratedStatement->args);
```suggestion
        $this->assertInstanceOf(TestStatement::class, $this->decoratedStatement);
        $this->assertCount(3, $this->decoratedStatement->args);
```

2022-01-02 18:05 UTC, Jean85 requested changes
Code looks fine, but the CI is broken. Please fix the Code Style (`make cs` will do it for you) and fix the test, it's failing for this error:

```
PHP Fatal error:  Class Sentry\SentryBundle\Tests\Tracing\Doctrine\DBAL\TestStatement must implement interface Traversable as part of either Iterator or IteratorAggregate in Unknown on line 0```

2022-01-18 13:19 UTC, ste93cry commented
@Jeroeny are you up to finish the PR? Otherwise I would be happy to make the changes needed to merge it on your behalf

2022-01-18 13:22 UTC, Jeroeny commented
@ste93cry Feel free to continue with these changes. I probably won't be able to spend time on it anytime soon.

2022-02-14 08:02 UTC, Jean85 approved these changes

2022-02-14 08:02 UTC, merged

2022-02-18 15:43 UTC, keichinger commented
@Jean85 do you have a rough ETA when a new version will be released that contains this PR?

2022-02-21 13:03 UTC, fbnfgc commented
@Jean85 thanks for your work on this issue. 

It looks like the `4.2.7` version has not been released yet. Do you need to push the tag manually?

2022-02-21 13:11 UTC, Jean85 commented
No, there's just a manual step in the process that requires a Sentry employee approval. It'll be here soon.