Support http_connect_timeout and http_timeout options
getsentry/sentry-symfony pull request #593
Opened 2022-01-19 10:19 UTC by matthew-gill

2022-01-19 15:31 UTC, Jean85 requested changes
This needs:
 * to lock against `sentry/sentry` which includes https://github.com/getsentry/sentry-php/pull/1282 (probably `^3.4`?)
 * a changelog entry
 * additions to the tests that cover the configuration

2022-01-20 09:15 UTC, Jean85 requested changes

2022-01-20 09:15 UTC, Jean85 commented on tests/DependencyInjection/Fixtures/php/full.php
> +        'http_connect_timeout' => 15,
As in https://github.com/getsentry/sentry-php/pull/1282#discussion_r787947940, you can't set a default here or you'll trigger errors if there is no default client available.

2022-01-20 11:11 UTC, matthew-gill commented on tests/DependencyInjection/Fixtures/php/full.php
> +        'http_connect_timeout' => 15,
If I set them as null I get 

```
Symfony\Component\Config\Definition\Exception\InvalidTypeException : Invalid type for path "sentry.options.http_timeout". Expected "int", but got "null".
```

How do you suggest to fix that? Would it be removing it from the fixture file and just creating a fixture which contains those options?

2022-01-20 11:13 UTC, matthew-gill commented on tests/DependencyInjection/Fixtures/php/full.php
> +        'http_connect_timeout' => 15,
For what it's worth, the fixture file does seem to contain a default value for `http_proxy`:

```
        'http_proxy' => 'proxy.example.com:8080',
```

2022-05-23 13:30 UTC, Jean85 commented
Build restarted, we have Psalm and a couple of other jobs failing.

2022-05-24 22:35 UTC, ste93cry commented
I rebased the PR on the latest `develop` and the situation is slightly better, but I can't understand why two jobs are still failing. Do you have any idea?

2022-05-29 16:46 UTC, ste93cry approved these changes

2022-05-30 09:03 UTC, Jean85 approved these changes

2022-05-30 09:05 UTC, merged