Add support for accessing dbal native connection
getsentry/sentry-symfony pull request #597
Opened 2022-02-04 15:52 UTC by simPod

Dbal V3 contains:

```php
/**
 * Connection interface.
 * Driver connections must implement this interface.
 *
 * @method resource|object getNativeConnection()
 */
interface Connection
```

2022-02-04 18:10 UTC, ste93cry requested changes
Thank you for the contribution! While making the required changes, please also add a CHANGELOG entry and the missing unit tests. For the latter, you can take a look at how they got implemented for the similar methods. Finally, please retarget the PR to the `develop` branch as this is a feature and not a bug fix and will be released with the next minor version

2022-02-04 18:10 UTC, ste93cry commented on src/Tracing/Doctrine/DBAL/TracingDriverConnection.php
> +            throw new LogicException(sprintf('The decoratedConnection %s does not support accessing the native connection.', \get_class($this->decoratedConnection)));
A more appropriate exception would be `BadMethodCallException`. Also, please change the message to `The connection "%s" does not support accessing the native connection` to stick with the convention we used elsewhere

2022-02-04 18:10 UTC, ste93cry commented on src/Tracing/Doctrine/DBAL/TracingDriverConnectionInterface.php
> +    public function getNativeConnection();
This is a breaking change. Please add the method as a `@method` annotation on the interface

2022-02-04 22:22 UTC, simPod commented on src/Tracing/Doctrine/DBAL/TracingDriverConnection.php
> +    public function getNativeConnection()
Are you aware the inherit docs is youselss as inheritance is implicit?

2022-02-04 22:23 UTC, simPod commented on src/Tracing/Doctrine/DBAL/TracingDriverConnection.php
> +            throw new LogicException(sprintf('The decoratedConnection %s does not support accessing the native connection.', \get_class($this->decoratedConnection)));
I copied it from dbal. I preferred to keep their code. Do you still want to change it?

2022-02-04 22:24 UTC, ste93cry commented on src/Tracing/Doctrine/DBAL/TracingDriverConnection.php
> +    public function getNativeConnection()
Yes, I've read about it. However, for consistency with the rest of the functions that are using it, I prefer to add it. We can always open a PR later to remove all the useless annotations

2022-02-04 22:27 UTC, ste93cry commented on src/Tracing/Doctrine/DBAL/TracingDriverConnection.php
> +            throw new LogicException(sprintf('The decoratedConnection %s does not support accessing the native connection.', \get_class($this->decoratedConnection)));
Yes please, we're always throwing a `BadMethodCallException` in similar cases so I prefer to keep doing it here too for consistency. Moreover, I don't think that a `LogicException` is appropriate to be honest as there is no error of logic here, but just a method you're calling when you should not. Message instead doesn't change much, it's just nitpicking 😃

2022-02-04 23:08 UTC, simPod commented
Aight, thanks for review, you'll have it tomorrow evening CET

On Fri, Feb 4, 2022, 23:27 Stefano Arlandini ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/Tracing/Doctrine/DBAL/TracingDriverConnection.php
> <https://github.com/getsentry/sentry-symfony/pull/597#discussion_r799855603>
> :
>
> > @@ -193,6 +194,15 @@ public function getWrappedConnection(): DriverConnectionInterface
>
>          return $this->decoratedConnection;
>
>      }
>
>
>
> +    public function getNativeConnection()
>
> +    {
>
> +        if (!method_exists($this->decoratedConnection, 'getNativeConnection')) {
>
> +            throw new LogicException(sprintf('The decoratedConnection %s does not support accessing the native connection.', \get_class($this->decoratedConnection)));
>
>
> Yes please, we're always throwing a BadMethodCallException in similar
> cases so I prefer to keep doing it here too for consistency. Moreover, I
> don't think that a LogicException is appropriate to be honest as there is
> no error of logic here, but just a method you're calling when you should
> not. Message instead doesn't change much, it's just nitpicking 😃
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/getsentry/sentry-symfony/pull/597#discussion_r799855603>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACQAJKJYDOPK4ZQSLD6PHLUZRHGDANCNFSM5NSEQVMA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-02-06 16:50 UTC, ste93cry commented
I think we can declare a `NativeDriverConnectionInterface` interface that extends `TracingDriverConnectionInterface` and declares the `getNativeConnection()` method. This class would be declared in the same file of the file and we should mock it instead of the original one. The Doctrine team did the same [here](https://github.com/doctrine/dbal/commit/d9f969b366fcd4c7def89372b9c198edb2cc9fe5#diff-5f131af5ae726c9af5168551d124cbaea01bfe448e55aa5c33c9772829b9d359), so it should work

2022-02-07 08:10 UTC, simPod commented
Ok done

2022-02-14 18:20 UTC, ste93cry requested changes
Can you please add the missing `testGetNativeConnectionThrowsExceptionIfDecoratedConnectionDoesNotImplementMethod` test method so that we cover the exception path? Note that since the class of the connection is anonymous, you should use `expectExceptionMessageMatches`

2022-02-14 18:20 UTC, ste93cry commented on src/Tracing/Doctrine/DBAL/TracingServerInfoAwareDriverConnection.php
> +use function method_exists;
We never import the functions. Please revert these changes, and run the linter to add the appropriate `\` where needed

2022-02-14 18:20 UTC, ste93cry commented on tests/Tracing/Doctrine/DBAL/TracingServerInfoAwareDriverConnectionTest.php
> +            ->willReturn($nativeConnection);
Please add the expectation on the number of times that the method should be called

2022-02-14 18:20 UTC, ste93cry commented on tests/Tracing/Doctrine/DBAL/TracingDriverConnectionTest.php
> +        $decoratedConnection->method('getNativeConnection')
Please add the expectation on the number of times that the method should be called

2022-02-14 21:33 UTC, simPod commented on src/Tracing/Doctrine/DBAL/TracingDriverConnection.php
> +use BadMethodCallException;
Ok. BTW it's better to import it (micro-optimalization)

2022-02-14 21:36 UTC, simPod commented on src/Tracing/Doctrine/DBAL/TracingDriverConnection.php
> +use BadMethodCallException;
ok not really since you add `\`. Dunno, kinda messy 🤷🏾‍♀️ I've added it

2022-02-14 21:40 UTC, simPod commented on src/Tracing/Doctrine/DBAL/TracingDriverConnection.php
> +use BadMethodCallException;
Btw 2: the linter forced me to change `\method_exists` to `method_exists`

2022-02-14 21:41 UTC, simPod commented on src/Tracing/Doctrine/DBAL/TracingDriverConnection.php
> +     * @return resource|object
> Method Sentry\SentryBundle\Tracing\Doctrine\DBAL\TracingDriverConnection::getNativeConnection() has no return typehint specified.

2022-02-14 22:05 UTC, simPod commented
Thanks for review, appreciate the strictnesss

2022-02-14 22:21 UTC, ste93cry commented on src/Tracing/Doctrine/DBAL/TracingDriverConnection.php
> +use BadMethodCallException;
Yes it makes sense, only some functions are optimized when adding the `\` prefix, that's why the linter does not add it to all of them

2022-02-14 22:23 UTC, simPod commented on src/Tracing/Doctrine/DBAL/TracingDriverConnection.php
> +use BadMethodCallException;
Php first looks for local `method_exists`, then for `\method_exists` when `\` or `use` is not used, doesn't it?

2022-02-14 22:32 UTC, ste93cry commented on src/Tracing/Doctrine/DBAL/TracingDriverConnection.php
> +use BadMethodCallException;
That's how it should work, yes. But, as far as I understood some time ago when I read what the `native_function_invocation` rule does, there are some functions that are treated in some special way and are thus optimized by the Zend engine, but I never investigated too much about this. What I know is that PHP-CS-Fixer has a few settings for this rule, and we're using the one that adds the prefix only to these special functions

2022-02-14 22:33 UTC, ste93cry commented on src/Tracing/Doctrine/DBAL/TracingDriverConnection.php
> +     * @return resource|object
Is PHPStan throwing this error? Weird, it should be able to read the `@method` annotations 🤔 Anyway, it's not that important, it was just a matter of not repeating the typehint

2022-02-14 22:35 UTC, simPod commented
Yup, it was phpstan

On Mon, Feb 14, 2022, 23:33 Stefano Arlandini ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/Tracing/Doctrine/DBAL/TracingDriverConnection.php
> <https://github.com/getsentry/sentry-symfony/pull/597#discussion_r806293990>
> :
>
> > @@ -164,6 +165,20 @@ public function rollBack(): bool
>
>          });
>
>      }
>
>
>
> +    /**
>
> +     * ***@***.***}
>
> +     *
>
> +     * @return resource|object
>
>
> Is PHPStan throwing this error? Weird, it should be able to read the
> @method annotations 🤔 Anyway, it's not that important, it was just a
> matter of not repeating the typehint
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/getsentry/sentry-symfony/pull/597#discussion_r806293990>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACQAJNVWFMKDN4M2JJBNU3U3F7LDANCNFSM5NSEQVMA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-02-14 22:49 UTC, ste93cry approved these changes
Thank you for the contribution and the patience making all the changes! LGTM 🥳

2022-02-14 22:50 UTC, merged