Tracing: symfony http client
getsentry/sentry-symfony pull request #606
Opened 2022-03-23 21:11 UTC by alekitto

- Add tracing to symfony http client
- Add `sentry-trace` header to requests to support distributed tracing

Due to a recent change in symfony's `Container::getParameter` docblock, psalm php version has been increased to 8.1. Otherwise `unknown class \UnitEnum` errors would be emitted

2022-04-09 21:20 UTC, ste93cry requested changes
Thank you for the contribution. I did a first round of code review and left some comments here and there. Besides adding a CHANGELOG entry and some more tests, this is a good foundation for sure for this feature and I can't wait to see it merged 🥳

2022-04-09 21:20 UTC, ste93cry commented on src/Tracing/HttpClient/AbstractTraceableResponse.php
> +     * @throws ServerExceptionInterface      On a 5xx when $throw is true
There's no need to copy all this text from the parent class, we can just use `{@inheritdoc}`

2022-04-09 21:20 UTC, ste93cry commented on src/Tracing/HttpClient/AbstractTraceableResponse.php
> +        if ($throw) {
I'm not sure I get why we have to reimplement the logic of this method instead of simply forwarding the call to the decorated response. Am I missing something?

2022-04-09 21:20 UTC, ste93cry commented on src/Tracing/HttpClient/AbstractTraceableResponse.php
> +            $this->span = null;
Are we setting the property to `null` to prevent some memory leak or what else?

2022-04-09 21:20 UTC, ste93cry commented on src/Tracing/HttpClient/AbstractTraceableResponse.php
> +            if ($r->span) {
To make it clear to the reader what the intention is, let's make the comparison explicit by adding `!== null`

2022-04-09 21:20 UTC, ste93cry commented on src/Tracing/HttpClient/AbstractTraceableResponse.php
> +                $spanContext = new SpanContext();
I'm not sure I understand why we are creating this span. What do we want to measure specifically that is worth it?

2022-04-12 16:01 UTC, alekitto commented on src/DependencyInjection/Compiler/HttpClientTracingPass.php
> +            $container->register('.sentry.' . $id, TraceableHttpClient::class)
Agree, will change it

2022-04-12 16:22 UTC, alekitto commented on src/Tracing/HttpClient/AbstractTraceableResponse.php
> +            $this->span = null;
`finish` could be called multiple times (`getContent`, `getHeaders`, etc), setting it to null will prevent the overwrite of the span end time

2022-04-12 16:29 UTC, alekitto commented on src/Tracing/HttpClient/AbstractTraceableResponse.php
> +                $spanContext = new SpanContext();
Can't remember why I added it. Removing it, it was probably worthless.

2022-04-15 11:39 UTC, alekitto commented on src/aliases.php
> +    } elseif (\PHP_VERSION_ID >= 80000) {
Ok, I changed it to use `version_compare`, but please consider that there's a huge performance penalty in this case.
Using `PHP_VERSION_ID` and `Kernel::VERSION_ID` makes faster the execution of this file (which is executed every time the `vendor/autoload.php` is included, so on every request).

2022-04-15 11:40 UTC, alekitto commented on .github/workflows/static-analysis.yaml
> -        run: composer psalm -- --php-version=8.0
Ok, done

2022-04-15 11:41 UTC, alekitto commented on src/Tracing/HttpClient/AbstractTraceableHttpClient.php
> +            $span = $transaction->startChild($context);
You're right, changed

2022-04-15 11:43 UTC, alekitto commented on src/Tracing/HttpClient/AbstractTraceableHttpClient.php
> +            $context = new SpanContext();
👍

2022-04-15 11:43 UTC, alekitto commented on src/Tracing/HttpClient/AbstractTraceableHttpClient.php
> +            $context->setOp($method . ' ' . $url);
I've changed the operation to `'http.request'`, is it ok?

2022-04-15 11:44 UTC, alekitto commented on tests/Tracing/HttpClient/TraceableHttpClientTest.php
> +final class TraceableHttpClientTest extends TestCase
Done 👍

2022-04-15 11:46 UTC, alekitto commented on src/Tracing/HttpClient/AbstractTraceableResponse.php
> +        if ($throw) {
I've moved `toStream` into `TraceableResponseForV5/6` where it is safe to call the parent method

2022-04-15 13:52 UTC, ste93cry commented on src/Tracing/HttpClient/AbstractTraceableHttpClient.php
> +            $context->setOp($method . ' ' . $url);
No, it should be `http.client`. The reasons for using this value are: compatibility with the OpenTelemetry standard and that the `op` attribute is used by Sentry for categorization purposes, so it's better to stick to the convention used across SDKs when possible

2022-04-17 19:26 UTC, ste93cry commented on src/aliases.php
> +    } elseif (\PHP_VERSION_ID >= 80000) {
Indeed, accessing a constant is faster that calling a function. Speaking about performance, I'm not sure it changes much though because we have other calls to `version_compare()` that will make using the constant in just one place superfluous. To be clear, I have nothing against comparing the constant, but I would prefer to do it separately so that we can uniformate the code

2022-05-02 14:06 UTC, alekitto commented on src/Tracing/HttpClient/AbstractTraceableHttpClient.php
> +            $context->setOp($method . ' ' . $url);
Ok, done

2022-05-02 14:08 UTC, alekitto commented on src/aliases.php
> +    } elseif (\PHP_VERSION_ID >= 80000) {
Agree, I reverted to `version_compare`, I'll open a new PR after this for the comparison conversions

2022-05-11 22:59 UTC, ste93cry requested changes
Build is broken. Moreover, there's a lot of untested code (especially in the `AbstractTraceableResponse` class). It would be great if you could add at least a test for each method, which tests both the success path and the failure one (if there is any)

2022-05-11 22:59 UTC, ste93cry commented on src/Tracing/HttpClient/AbstractTraceableResponse.php
> +            }
Instead of copying this logic from the component itself, we could simply add a `catch` statement and rethrow the exception

2022-05-11 22:59 UTC, ste93cry commented on src/Tracing/HttpClient/AbstractTraceableResponse.php
> +            }
Instead of copying this logic from the component itself, we could simply add a `catch` statement and rethrow the exception

2022-05-11 22:59 UTC, ste93cry commented on src/Tracing/HttpClient/AbstractTraceableResponse.php
> +        foreach ($responses as $r) {
Please rename the variable to `$response`

2022-05-11 22:59 UTC, ste93cry commented on tests/DependencyInjection/Compiler/HttpClientTracingPassTest.php
> +class HttpClientTracingPassTest extends TestCase
This class can be marked `final`

2022-05-11 22:59 UTC, ste93cry commented on tests/DependencyInjection/Compiler/HttpClientTracingPassTest.php
> +        self::assertEquals(TraceableHttpClient::class, $container->findDefinition('http.client')->getClass());
Please use `$this->assert...()` instead of `self::assert...()` for consistency reasons with the rest of the code

2022-05-11 23:00 UTC, ste93cry commented on src/Tracing/HttpClient/AbstractTraceableHttpClient.php
> +            $context = new SpanContext();
Can we also add the description of the span? Otherwise, it appears as an anonymous `(unnamed span)` in the UI. Looking at the OpenTelemetry specs, we should not choose a name that has an high cardinality, and it appears that their official web instrumentation package simply collects the name as `HTTP $methodName`, which should be enough for us as well,

2022-05-30 12:49 UTC, alekitto commented
@ste93cry Why has this been closed? I did not have time to complete the tests in the last weeks, but I will work on this in the few days.

2022-05-30 13:27 UTC, ste93cry commented
Sorry, I did not meant to close it. I mistakenly deleted the `develop` branch while merging another PR and this one got closed as a consequence

2022-06-22 08:59 UTC, alekitto commented on src/DependencyInjection/SentryExtension.php
> +            throw new LogicException('Http client tracing support cannot be enabled because the symfony/http-client Composer package is not installed.');
Done.

2022-06-22 08:59 UTC, alekitto commented
I've added some tests and rebased the branch. All issues should be resolved now.

2022-06-23 08:00 UTC, Jean85 requested changes
Great work! Only one nitpick comment, and... should we also plan for some docs? It's not clear to me how this can be enabled, and what are the prerequisites.

2022-06-23 08:09 UTC, alekitto commented
Like `dbal`, `twig` and `cache` tracing, this is enabled by default if the component is installed (=> if class `Symfony\Component\HttpClient\HttpClient` exists).

There's only the `enabled` configuration option, so the only prerequisite is the `symfony/http-client` component to be installed

2022-06-29 15:23 UTC, Jean85 approved these changes
Great! LGTM! :+1:

2022-07-05 11:02 UTC, alekitto commented
> - the exception when tracing gets enabled but the package is missing (for which we have a dedicated CI job already)

I've tried to test the package with http-client removed from dev-deps, but is still there. `composer why symfony/http-client` outputs:

```
sentry/sdk                3.2.0    requires   symfony/http-client (^4.3|^5.0|^6.0)  
symfony/framework-bundle  v5.4.10  conflicts  symfony/http-client (<4.4)            
symfony/http-kernel       v5.4.10  conflicts  symfony/http-client (<5.0)            
```

Notably the `sentry/sdk` package requires `symfony/http-client` and cannot be removed. 
The test expecting the exception is present, but I really don't know how to invoke it :sweat_smile: 

Tests for `stream` method and `withOptions` are now OK

2022-07-05 15:09 UTC, Jean85 commented
`sentry/sdk` is just a package that auto-suggest the default for having a client implementation.

We can either leave it like this, or remove `sentry/sdk` in the CI to test that part. @ste93cry WDYT?

2022-07-05 15:26 UTC, ste93cry commented
I don't think we should change the CI to remove the package because we actually do require the `symfony/http-client` (even though indirectly), so the test doesn't really make sense in the context of what would happen in the real world.

2022-07-06 08:44 UTC, Jean85 approved these changes
Then this is ready IMO! :+1: good job!

2022-07-14 16:27 UTC, ste93cry approved these changes
Thank you @alekitto for the lovely work and the dedication to this contribution. LGTM!

2022-07-14 16:28 UTC, merged

2022-07-14 16:33 UTC, alekitto commented
Thanks @ste93cry and @Jean85 for the support and continuous review of this PR (and obviously for all the work on this bundle) :)

2022-11-24 14:02 UTC, cleptric commented
@alekitto hey, I know it's been a while since you implemented this.

While testing this feature, I noticed that correct span timing heavily relies on users calling `$response->getContent()` or `(array) $response`.

![Screenshot 2022-11-24 at 14 01 39](https://user-images.githubusercontent.com/6617432/203799894-ef36dcb1-bb88-411a-bf5f-12c3e9ebc909.png)

I'm doing a bunch of "fire & forget" GET requests. You can see the next `cache` span starts before the last `http.client` span is finished, as the span is finished once `__deconstruct` is called, which is obviously too late.

Did this pop up while working on this?

2022-11-25 22:08 UTC, alekitto commented
Hi @cleptric,
Sorry, I only saw your comment now.

I don't remember anything similar, but also I don't remember if I tested this particular case.
Anyway, reading the issue on symfony repository, it seems that the API design makes impossible to know exactly when the request finished without a method call; however, an `on_progress` callback could be added to the options to check if the request has been completed and stop the `Span`.

I don't know if this could be a viable approach...