Default $length to 0, as using null causes a deprecation with PHP8+
getsentry/sentry-symfony pull request #613
Opened 2022-04-05 22:07 UTC by cjunge-work

When using PHP8+ with Doctrine DBALv2 and calling `PDOStatement::bindParam()` with just 2 params causes a deprecation for passing null to an int param. The default in PDO is `0`, so this change defaults to 0 when calling the decorated statement.

Fixes #611

2022-04-06 22:58 UTC, ste93cry requested changes
Thank you for taking the time to contribute this change! Besides adding an entry to the CHANGELOG, I just have a doubt about why  the current solution does not work: if you call `bindParam` with up to 3 params, the `array_slice` should return an empty `array`, and the same thing should happen [here](https://github.com/doctrine/dbal/blob/2.13.8/lib/Doctrine/DBAL/Driver/PDOStatement.php#L87). As a consequence of this, PHP should fallback to the default value for the `$length` param 🤔

2022-04-06 22:58 UTC, ste93cry commented on tests/Tracing/Doctrine/DBAL/TracingStatementForV2Test.php
> +        $this->assertTrue($this->statement->bindParam('foo', $variable, ParameterType::STRING, 3));
The name of this method is now misleading because it's not true anymore that the `$length` param is forwarded only when explicitly set. Also, all the mess with the custom stub was done because PHPUnit generates the mock so that it always forwards all parameters defined in the method signature to the invocation matcher, regardless of how many you really use in the call. However, since we now forcefully pass `$length` with a proper value, we don't need special handling for it anymore. For this reason, we can just refactorize the `testBindParam()` method so that it uses a data provider where the input test cases are:

- `$length` param is `null` and `$decoratedStatement` receives `0`
- `$length` param is a number and `$decoratedStatement` receives that number

2022-04-06 23:15 UTC, cjunge-work commented
> Thank you for taking the time to contribute this change! Besides adding an entry to the CHANGELOG, I just have a doubt about why the current solution does not work: if you call `bindParam` with up to 3 params, the `array_slice` should return an empty `array`, and the same thing should happen [here](https://github.com/doctrine/dbal/blob/2.13.8/lib/Doctrine/DBAL/Driver/PDOStatement.php#L87). As a consequence of this, PHP should fallback to the default value for the `$length` param thinking

We don't run Sentry on our dev environments, and we have been unable to replicate this issue without Sentry enabled. I'm not sure why the DBAL PDOStatement is working fine but the Sentry TracingStatementv2 isn't.

I haven't done any in-depth exploration, but it appears to me that the default `null` on the tracing statement bindParam method becomes the default if it's not explicitly passed in. This then is passed to the DBALv2 Statement which simply extends PDOStatement. With <PHP8.1 it works fine (I guess PHP implicitly casts it to 0 or ignores it & uses the PDOStatement default), but under PHP8.1 with the changes to deprecate passing null to non-nullable internal function parameters (https://www.php.net/releases/8.1/en.php) the null is triggering the deprecation.

2022-04-07 23:42 UTC, cjunge-work commented
@ste93cry I think I've found the smoking gun: the array_slice offset appears to be wrong! https://3v4l.org/7NhQT#v8.1.4

2022-04-08 00:11 UTC, cjunge-work commented
@ste93cry I deleted my previous comment as it was wrong. Here's an example showing how the explicit null triggers the deprecation, but not providing the param doesn't: https://3v4l.org/biaIs#v8.1.4. I'm still not sure why the deprecation is being triggered in Sentry.

2022-04-08 06:51 UTC, Jean85 commented
Can we add a unit test to trigger the deprecation in our CI? Or is it already there, and then why it's not failing?

2022-04-08 07:56 UTC, ste93cry commented
>the explicit null triggers the deprecation, but not providing the param doesn't

That's the expected behaviour. If you explicitly pass `null`, then it's up to you to know that you will trigger a deprecation. Silly question: are you sure that there is no other code that pass that param explicitly?

2022-04-10 22:25 UTC, cjunge-work commented
@ste93cry My point was that the explicit null triggers the deprecation, when not using Sentry, so it's not a side-effect of the code.

```
<?php

declare(strict_types=1);

use Doctrine\DBAL\Driver\Connection;
use Psr\Container\ContainerInterface;

class aClass
{
    public function __construct(ContainerInterface $container, Connection $connection)
    {
        parent::__construct($container);

        $this->connection = $connection;
    }

    public function aMethod($applicationAverageTime) {
        $statement = $this->connection->prepare('...');
// ...
        $statement->bindParam(':applicationAverageTime', $applicationAverageTime); // <---
// ...
    }
}
```
that's the line that our last deprecation was triggered on, we don't tend to even use the type.

2022-04-23 16:31 UTC, ste93cry commented
Sorry for being silent. I reproduced the issue locally, and I found out that the problem originates from [here](https://github.com/doctrine/dbal/blob/dc9b3c3c8592c935a6e590441f9abc0f9eba335b/lib/Doctrine/DBAL/Statement.php#L143). Basically, since the statement is wrapped by our `TracingStatementForV2` class, the `instanceof PDOStatement` returns `false`. Then, the `$length` parameter is explicitly passed to the `bindParam` method with a `null` value and this triggers the deprecation. I would say that the check in the DBAL is pretty weak as-is, and should be changed to take into account the fact that the statement could be wrapped. Anyway, your fix is good, so if you are willing to fix the requested changes I would happily merge this PR.

2022-05-01 22:21 UTC, ste93cry approved these changes
I took the time to finish your work, hopefully you don't mind. Thank you for your contribution, I will release the fix in the next days

2022-05-01 22:22 UTC, merged