SentryTestCommand > Add `#[AsCommand]` attribute
getsentry/sentry-symfony pull request #635
Opened 2022-05-27 08:59 UTC by ruudk

This fixes a deprecation on Symfony 6.1:
```
Since symfony/console 6.1: Relying on the static property "$defaultName" for setting a command name is deprecated. Add the "Symfony\Component\Console\Attribute\AsCommand" attribute to the "Sentry\SentryBundle\Command\SentryTestCommand" class instead.
```

2022-05-27 09:33 UTC, Jean85 requested changes
Couldn't we simply add the attribute, so we can avoid both the deprecation and the separation between the command and its name? Attributes are parsed as comments in older PHP versions.

2022-05-27 09:34 UTC, ruudk commented
I tried that first (adding AsCommand attribute and keeping the `$defaultName` property) but unfortunately, that gives us this error:
```
The "Symfony\Component\Console\Command\Command::$defaultName" property is considered final. You should not override it in "Sentry\SentryBundle\Command\SentryTestCommand".
```

2022-05-27 15:37 UTC, Jean85 requested changes
Ok so the change LGTM.

Can you please add a changelog entry then?

2022-05-28 05:36 UTC, ruudk commented
@Jean85 done!

2022-05-28 16:22 UTC, Jean85 approved these changes

2022-05-28 16:22 UTC, merged