Drop Symfony support below 4.4
getsentry/sentry-symfony pull request #643
Opened 2022-06-21 11:37 UTC by Jean85

I'm opening this as a draft since it may require some discussion (or dropping some pieces of code no longer used).

3.4 is unsupported since last November: https://symfony.com/releases/3.4
Everything between that and 4.4 (since it's an LTS) is unsupported too.

Hence, dropping the support now makes sense. This PR is targeting `develop`, so it would land in the next minor (4.4 as of now).

2022-06-23 17:24 UTC, ste93cry requested changes
The `RequestListenerTest ::testHandleKernelRequestEvent()` method is still using a data provider that was meant for Symfony < `4.4`

2022-06-23 17:24 UTC, ste93cry commented on src/DependencyInjection/SentryExtension.php
> -                        FatalErrorException::class,
Are you sure we can stop ignoring this exception? In Symfony `4.4` it is still present

2022-06-24 07:34 UTC, Jean85 commented on src/DependencyInjection/SentryExtension.php
> -                        FatalErrorException::class,
Mh maybe you're right, I'm not sure how 4.4 handles this deprecation. Let's keep it safe, I'll revert this piece.

2022-06-25 17:11 UTC, ste93cry requested changes
There are still things to delete: in the `SubRequestListenerTest` class some of the data providers are still splitted per-Symfony version, and probably we can also remove the `KernelEventForwardCompatibilityTrait` trait. I suggest to look for occurences of the `version_compare` or `Kernel::VERSION` keywords

2022-06-27 10:23 UTC, Jean85 commented
`isMasterRequest` got deprecated in 5.3, `KernelEventForwardCompatibilityTrait` is still needed: [KernelEventForwardCompatibilityTrait](https://github.com/symfony/symfony/blob/a6af0ddb2bf79a8cec20478e4fd8b7bbe83bd1b6/src/Symfony/Component/HttpKernel/Event/KernelEvent.php#L84-L86).

I took care of the rest.

2022-06-28 17:49 UTC, merged