Support logging the impersonator user, if any
getsentry/sentry-symfony pull request #647
Opened 2022-07-06 16:34 UTC by ste93cry

Fixes #642 by logging the impersonator user as part of the metadata of the [User Interface](https://develop.sentry.dev/sdk/event-payloads/user/). @hunhejj given that you asked for this feature, would you mind trying this out and see if it works?

2022-07-07 08:40 UTC, Jean85 requested changes

2022-07-07 09:39 UTC, ste93cry commented on CHANGELOG.md
> +- Support logging the impersonator user, if any (#647)
Actually, `impersonator` is the right word, as per doc:

>In some cases, you may need to get the object that represents the impersonator user rather than the impersonated user. 
>https://symfony.com/doc/current/security/impersonating_user.html#finding-the-original-user

2022-07-11 06:49 UTC, hunhejj commented
I tried to test it on our project @ste93cry but unfortunately I get way too many conflicts when trying to install the branch directly.

2022-07-11 06:50 UTC, hunhejj commented
Btw. in your original thread you suggested using a dedicated tag but I see in the implementation that you ended up with user meta. Out of curiosity what is the advantage of it?

2022-07-13 21:53 UTC, ste93cry commented on tests/EventListener/RequestListenerTest.php
> +     * @dataProvider handleKernelRequestEventForSymfonyVersionLowerThan60DataProvider
I tried to rearrange the test cases so that they are executed as much as possible closer to the Symfony version they belongs to, at the cost of duplicating some of them in the various data providers. The main things to consider though is that we have to test the following ranges of versions: `<5.4`, `>=5.4 && <6.0` and `>=5.4`

2022-07-13 22:17 UTC, ste93cry commented
>you suggested using a dedicated tag but I see in the implementation that you ended up with user meta

Right, I didn't check at that time and I though that the user was logged as a tag, but actually there is a specific [`User Interface`](https://develop.sentry.dev/sdk/event-payloads/user/) provided by Sentry to store the user information that we were already using. From the UI's perspective, the only difference is that the impersonator user is shown in the section dedicated to the user details instead of the section of the tags. However, it looks like all the extra fields that belongs to that `Interface` are not indexed and so aren't searchable. I think that for consistency purposes and also because "it feels more appropriate" we should keep going this way, but, as a side note, I would support the idea of asking Sentry if it was possible to make searchable all the extra fields of the user.

2022-07-15 09:49 UTC, merged