Switch to MIT license
getsentry/sentry-symfony pull request #697
Opened 2023-02-16 14:13 UTC by cleptric

The license of our SDKs should be MIT.

https://open.sentry.io/licensing/

Part of https://github.com/getsentry/team-ospo/issues/56.

2023-02-16 14:23 UTC, Jean85 requested changes
The identifier in `composer.json` should be changed too.

2023-02-16 14:27 UTC, cleptric commented
Good point, updated

2023-02-16 16:08 UTC, chadwhitacre approved these changes

2023-02-16 16:52 UTC, chadwhitacre approved these changes
I've reviewed https://github.com/getsentry/sentry-symfony/search?q=license and this lgtm. 👍

2023-02-16 17:07 UTC, cleptric commented
@Jean85 Would you mind not blocking merging by requesting changes? A normal review comment suffices, I won't merge it without addressing it 😄

2023-02-16 17:11 UTC, chadwhitacre commented
> Would you mind not blocking merging by requesting changes?

I rerequested from @Jean85 and approved, I think we're unblocked?

2023-02-16 17:16 UTC, merged

2023-02-17 10:01 UTC, Jean85 commented
> @Jean85 Would you mind not blocking merging by requesting changes? A normal review comment suffices, I won't merge it without addressing it smile

Sorry, I didn't realize I was blocking!