Remove advertisement of abandoned package
getsentry/sentry-symfony pull request #709
Opened 2023-03-29 19:51 UTC by stayallive

> https://packagist.org/packages/pugx/sentry-sdk

This package is abandoned because `sentry/sdk` does the exact same now since we switched to using the Symfony HTTP client by default. So we should remove those instructions from the README since they no longer apply.

2023-03-29 21:13 UTC, Jean85 requested changes
Shouldn't we remove the part above too, that suggests to require an HTTP client manually? Or at least we should update that citing the behavior of the new HTTPlug plugin.

2023-03-30 07:55 UTC, Jean85 approved these changes

2023-03-30 07:55 UTC, Jean85 commented on README.md
> +If you don't have a compatible HTTP client and/or message factory implementation installed `php-http/discovery` will try to install it for you using a Composer plugin.
I would move this before the "If you want to use a different HTTP client" part, do you agree?

2023-03-30 08:17 UTC, stayallive commented on README.md
> +If you don't have a compatible HTTP client and/or message factory implementation installed `php-http/discovery` will try to install it for you using a Composer plugin.
I figured that as long as we keep `sentry/sdk` in here that wouldn't make much sense unless you replace `sentry/sdk` so I figured it would be best to keep it lower until we remove `sentry/sdk` completely since that plugin can be safely ignored as long as we ship with a client out-of-the-box. But I'd be happy to move it higher if you feel that is better!

2023-04-04 08:51 UTC, merged