Introduce TracingDriverForV32 for DBAL `>= 3.2`
getsentry/sentry-symfony pull request #723
Opened 2023-06-06 13:21 UTC by ruudk

This driver does not implement the deprecated `VersionAwarePlatformDriver`.

It's automatically picked when `doctrine/dbal` version `3.2.0` or higher is installed.

Fixes #579

2023-06-06 13:37 UTC, ruudk commented
@cleptric Any idea why the tests are not running anymore? It worked the first push, but then stopped. I feel there is an error on the workflow (that I modified) but I cannot see it.

2023-06-06 17:32 UTC, cleptric commented
It looks like the latest version of PHPCS contains some incompatible changes with prior versions. You might pin the version to something below 3.17 to get the tests passing.

2023-06-06 17:48 UTC, ruudk commented
@cleptric Done in https://github.com/getsentry/sentry-symfony/pull/723/commits/df8b4b8bd91abe61d9474a8e1fbed44273f5417c, we're green now.

2023-06-07 06:53 UTC, ruudk commented
@ste93cry @Jeroeny If you have time, I would really appreciate a review on this. Is this the direction to go? Please let me know, happy to make any changes.

2023-06-07 09:26 UTC, ste93cry requested changes

2023-06-07 09:26 UTC, ste93cry commented on .github/workflows/tests.yaml
>              dependencies: lowest
Given that these jobs are testing the `lowest` dependencies, shouldn't we specify `doctrine-dbal ^2.13` for all of them?

2023-06-07 09:28 UTC, ruudk commented on src/aliases.php
> +        if (class_exists(InstalledVersions::class) && version_compare(InstalledVersions::getVersion('doctrine/dbal') ?? '0', '3.2', '>=')) {
hmmm, if you can tell me what? 

Why not require composer v2? It was released on Oct 24, 2020.

2023-06-07 09:29 UTC, ruudk commented on composer.json
> +    "conflict": {
This is done because `php-cs-fixer` on `main` is broken! I will revert this, but that means PHP-CS-Fixer will stay red. Not going to fix this.

2023-06-07 09:32 UTC, ste93cry commented on composer.json
> +    "conflict": {
I understand the reason behind why you want to restrict the version of `PHP-CS-Fixer`, but this is not the right way as it will affect who installs `sentry/sentry-symfony` and not just us. That's why I'm suggesting to restrict the version under `require-dev`. Am I missing something?

2023-06-07 09:34 UTC, ruudk commented on composer.json
> +    "conflict": {
I didn't understand, I got it now. Thanks.

2023-06-07 09:43 UTC, cleptric commented on src/aliases.php
> +        if (class_exists(InstalledVersions::class) && version_compare(InstalledVersions::getVersion('doctrine/dbal') ?? '0', '3.2', '>=')) {
Because of https://develop.sentry.dev/sdk/philosophy/#compatibility-is-king.

2023-06-07 09:44 UTC, ste93cry commented on src/aliases.php
> +        if (class_exists(InstalledVersions::class) && version_compare(InstalledVersions::getVersion('doctrine/dbal') ?? '0', '3.2', '>=')) {
>hmmm, if you can tell me what?

I believe you meant to ask what you could use to discern the version of the DBAL. I think that one possibility could be to check that `Doctrine\DBAL\Logging\Driver` class exists, as it got introduced with version `3.2`

>Why not require composer v2?

No particular reason for me, but I'm pretty sure the Sentry guys would not be happy to make this package not be installable with Composer 1 as they are quite demanding on what must be supported by the SDK

2023-06-07 09:48 UTC, ruudk commented on src/aliases.php
> +        if (class_exists(InstalledVersions::class) && version_compare(InstalledVersions::getVersion('doctrine/dbal') ?? '0', '3.2', '>=')) {
Removed it and now check for the existence of `\Doctrine\DBAL\Exception\SchemaDoesNotExist`
https://github.com/doctrine/dbal/compare/3.1.5...3.2.0

2023-06-07 09:48 UTC, ruudk commented on tests/DoctrineTestCase.php
> +        return InstalledVersions::isInstalled('doctrine/dbal');
Removed

2023-06-07 09:49 UTC, ruudk commented on .github/workflows/tests.yaml
>              dependencies: lowest
Done

2023-06-07 09:50 UTC, ruudk commented
Applied feedback, we're green again.

2023-06-07 21:31 UTC, ste93cry requested changes

2023-06-07 21:31 UTC, ste93cry commented on tests/DoctrineTestCase.php
> +            && !self::isDoctrineDBALVersion3Point2Installed();
With this change, every test that was meant to run with Doctrine DBAL `3.x` will not work anymore when version `3.2` is installed. I suggest to check the proper version by eventually combining `isDoctrineDBALVersion3Installed()` and `isDoctrineDBALVersion3Point2Installed()` in each place where it is needed

2023-06-08 06:43 UTC, ruudk commented on tests/DoctrineTestCase.php
> +            && !self::isDoctrineDBALVersion3Point2Installed();
Sharp. Fixed now.

2023-06-08 08:50 UTC, ruudk commented
I didn't like the Point either... but 32 also feels weird. Anyway, since that's the convention, let's follow that.

2023-06-08 08:52 UTC, ste93cry commented
Yea, totally agree on everything you said 👍

2023-06-09 12:15 UTC, ruudk commented
Can this be merged? 🙏

2023-06-12 05:38 UTC, merged

2024-01-09 08:20 UTC, Kushnerevich commented
Any updates? Are looking forward to

2024-01-09 08:39 UTC, Jean85 commented
This is released since [4.9.0](https://github.com/getsentry/sentry-symfony/releases/tag/4.9.0)

2024-01-09 08:42 UTC, ste93cry commented
Nope, it was reverted in [`4.9.2`](https://github.com/getsentry/sentry-symfony/releases/tag/4.9.2). I don't remember exactly why, but I remember there was something in DBAL 3 that was missing in previous versions to have a fully working solution that was also backwards-compatible