Make TracingDriverForV32 implements VersionAwarePlatformDriver to handle platform version
getsentry/sentry-symfony pull request #731
Opened 2023-06-16 14:46 UTC by jdecool

Fix https://github.com/getsentry/sentry-symfony/issues/730

As discussed in the issue, I had the `createDatabasePlatformForVersion` method to handle the platform version.

2023-06-16 14:58 UTC, ste93cry commented
We need to implement the method without implementing the interface, otherwise we trigger again the deprecation. Please also add some tests for the new method 🙏

2023-06-16 16:06 UTC, ste93cry commented
>Do you prefer I've implement the test in an other way ?

Since the whole point of this class is to decouple from the `VersionAwarePlatformDriver` deprecated interface, I don't think we should use it in the tests either. What about mocking the `Driver` interface using `getMockBuilder()` and then using `addMethods()` on it to configure the `createDatabasePlatformForVersion()` method? Or, we could create a fake interface with that method declared and then simply use `createMock()` on it, similar to what we did in [`TracingDriverForV2`](https://github.com/getsentry/sentry-symfony/blob/707212c4330ccf2d2790f0f0a7036f4ace66fa7b/tests/Tracing/Doctrine/DBAL/TracingDriverForV2Test.php#L192)

2023-06-16 18:59 UTC, jdecool commented
I choose to create a fake interface.

2023-06-16 22:49 UTC, ste93cry requested changes
Apart from a small nitpick, it looks good to me. Do you mind testing that it works well in your project and confirm it?

2023-06-16 22:49 UTC, ste93cry commented on tests/Tracing/Doctrine/DBAL/TracingDriverForV32Test.php
> +        public function createDatabasePlatformForVersion($version);
Given that the method does not exist in the parent interface and when it will be added it will be typehinted anyway, it makes more sense to avoid the PHPDoc

```suggestion
        public function createDatabasePlatformForVersion(string $version): AbstractPlatform;
```

2023-06-17 05:43 UTC, jdecool commented on tests/Tracing/Doctrine/DBAL/TracingDriverForV32Test.php
> +        public function createDatabasePlatformForVersion($version);
✅

2023-06-17 10:00 UTC, ste93cry approved these changes
Good work, thank you!

2023-06-17 10:03 UTC, merged

2023-06-17 11:39 UTC, jdecool commented
Thanks @ste93cry for your help 🙏🏼