Move span tags to span data
getsentry/sentry-symfony pull request #743
Opened 2023-07-05 09:38 UTC by cleptric

Closes #728

2023-07-05 11:13 UTC, ste93cry requested changes

2023-07-05 11:13 UTC, ste93cry commented on src/Tracing/Doctrine/DBAL/AbstractTracingStatement.php
> +    protected $spanData;
Technically speaking, this is a BC... We should leave the old property (and likely initialize it with an empty `array`), mark it deprecated and add `$spanData`

2023-07-05 11:13 UTC, ste93cry commented on src/Tracing/Doctrine/DBAL/TracingDriverConnectionFactory.php
> +        if ($databasePlatform instanceof AbstractMySQLPlatform) {
I suggest to use a `switch (true)` where each case is `$databasePlatform instanceof ...`

2023-07-06 08:35 UTC, HazAT approved these changes

2023-07-06 09:05 UTC, ste93cry approved these changes

2023-07-06 09:05 UTC, merged