Add jobs for PHP `8.3` to the CI
getsentry/sentry-symfony pull request #767
Opened 2023-10-22 21:39 UTC by ste93cry

With PHP "8.3" coming in November 2023, it's time to run the CI for that version as well so that we're ready for its release.

2023-10-23 07:29 UTC, Jean85 requested changes

2023-10-23 07:29 UTC, Jean85 commented on .github/workflows/static-analysis.yaml
> +          php-version: '8.3'
This is failing, and PHP-CS-Fixer is slow to support newer language versions. We should stick to 8.2 here
```suggestion
          php-version: '8.2'
```

2023-10-24 21:15 UTC, ste93cry commented on .github/workflows/static-analysis.yaml
> +          php-version: '8.3'
>PHP-CS-Fixer is slow to support newer language versions

It makes me sad, but I agree. I wanted to run the tol on PHP `8.3` just for the sake of consistency with the other jobs, but I remember that in the past we had to wait on average a long time for a compatible version to be released

2023-10-24 21:38 UTC, ste93cry commented
@cleptric I think it's pointless to retest all PHP versions just to make sure they work without optional packages installed, so I removed some jobs from the GitHub Workflow and changed the matrix so that only the oldest and newest PHP versions of each major are tested. However, as you can see from the following image, some jobs are still flagged as required checks for the CI to pass. Maybe the repo settings need to be adjusted accordingly?

![immagine](https://github.com/getsentry/sentry-symfony/assets/1770485/71fddc17-3e5c-4ba4-b1e7-d88b3d6fc56d)

2023-10-25 09:56 UTC, cleptric commented
The required checks haven been removed.

2023-10-25 21:08 UTC, Jean85 approved these changes

2023-10-25 21:10 UTC, merged